"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import type { Locale } from "@/lib/i18n/locale";
import { intlLocale } from "@/lib/i18n/locale";
import { dictionary } from "@/lib/i18n/dictionary";
import { getWhatsappLink } from "@/lib/social";

type Service = { id: string; name: string; duration_minutes: number; price_cents: number; deposit_enabled: boolean | null; deposit_percent: number | null; category: { name: string } | { name: string }[] | null };
type Settings = { deposit_enabled: boolean; deposit_percent: number; online_payment_options?: ("deposit" | "full")[]; allow_booking_without_online_payment?: boolean; web_payments_enabled?: boolean } | null;
type Slot = { specialist_id: string | null; starts_at: string; ends_at: string };
type Booking = { public_code: string; price_cents: number; deposit_due_cents: number; deposit_percent: number };
type LockLevel = "none" | "category" | "service";
type BookingDraft = Partial<{ step:number; category:string; selectedId:string; date:string; selectedSlot:Slot; form:{ fullName:string; phone:string; email:string; notes:string } }>;
const categoryName = (service: Service) => Array.isArray(service.category) ? service.category[0]?.name : service.category?.name;
const mexicoDate = () => new Intl.DateTimeFormat("en-CA", { timeZone: "America/Mexico_City", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
const parseCalendarDate = (value: string) => new Date(`${value}T12:00:00`);
const toDateValue = (value: Date) => `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, "0")}-${String(value.getDate()).padStart(2, "0")}`;
const readBookingDraft = (): BookingDraft => { if (typeof window === "undefined") return {}; try { return JSON.parse(sessionStorage.getItem("ola-bonita:booking-draft:v1") || "{}"); } catch { sessionStorage.removeItem("ola-bonita:booking-draft:v1"); return {}; } };
const bookingWhatsappKey = "ola-bonita:booking-whatsapp:v1";

function BookingCalendar({ date, min, max, locale, onSelect }: { date: string; min: string; max: string; locale: Locale; onSelect: (date: string) => void }) {
  const [view, setView] = useState(() => { const selected = parseCalendarDate(date); return new Date(selected.getFullYear(), selected.getMonth(), 1); });
  const minDate = parseCalendarDate(min); const maxDate = parseCalendarDate(max);
  const monthLabel = new Intl.DateTimeFormat(intlLocale(locale), { month: "long" }).format(view);
  const weekdays = Array.from({ length: 7 }, (_, index) => new Intl.DateTimeFormat(intlLocale(locale), { weekday: "short" }).format(new Date(2023, 0, 1 + index)).replace(".", ""));
  const firstWeekday = view.getDay(); const daysInMonth = new Date(view.getFullYear(), view.getMonth() + 1, 0).getDate();
  const changeMonth = (offset: number) => setView((current) => new Date(current.getFullYear(), current.getMonth() + offset, 1));
  const previousMonth = new Date(view.getFullYear(), view.getMonth() - 1, 1); const nextMonth = new Date(view.getFullYear(), view.getMonth() + 1, 1);
  const isBeforeMin = previousMonth < new Date(minDate.getFullYear(), minDate.getMonth(), 1); const isAfterMax = nextMonth > new Date(maxDate.getFullYear(), maxDate.getMonth(), 1);
  return <div className="booking-calendar" aria-label={locale === "es" ? "Calendario para elegir fecha" : "Calendar to choose a date"}>
    <div className="booking-calendar-heading"><div><span>{String(view.getMonth() + 1).padStart(2, "0")}</span><strong>{monthLabel}</strong></div><em>{view.getFullYear()}</em><div className="booking-calendar-controls"><button type="button" aria-label={locale === "es" ? "Mes anterior" : "Previous month"} disabled={isBeforeMin} onClick={() => changeMonth(-1)}>←</button><button type="button" aria-label={locale === "es" ? "Mes siguiente" : "Next month"} disabled={isAfterMax} onClick={() => changeMonth(1)}>→</button></div></div>
    <div className="booking-calendar-weekdays">{weekdays.map((weekday) => <span key={weekday}>{weekday}</span>)}</div>
    <div className="booking-calendar-days">{Array.from({ length: firstWeekday }, (_, index) => <span key={`blank-${index}`} aria-hidden="true" />)}{Array.from({ length: daysInMonth }, (_, index) => { const day = new Date(view.getFullYear(), view.getMonth(), index + 1); const value = toDateValue(day); const unavailable = day < minDate || day > maxDate; return <button type="button" key={value} disabled={unavailable} className={value === date ? "selected" : ""} aria-pressed={value === date} onClick={() => onSelect(value)}>{index + 1}</button>; })}</div>
  </div>;
}

export function BookingServicePicker({ services, settings, locale, preselectedServiceId, preselectedCategory }: { services: Service[]; settings: Settings; locale: Locale; preselectedServiceId?: string; preselectedCategory?: string }) {
  const t = dictionary[locale].booking;
  const money = useMemo(() => new Intl.NumberFormat(intlLocale(locale), { style: "currency", currency: "MXN", maximumFractionDigits: 0 }), [locale]);
  const categories = useMemo(() => [...new Set(services.map(categoryName).filter((name): name is string => Boolean(name)))], [services]);
  const preselectedService = preselectedServiceId ? services.find((service) => service.id === preselectedServiceId) : undefined;
  const categoryMatch = !preselectedService && preselectedCategory && categories.includes(preselectedCategory) ? preselectedCategory : undefined;
  const [initialDraft] = useState(readBookingDraft);
  const validDraftService = initialDraft.selectedId && services.some((service) => service.id === initialDraft.selectedId) ? initialDraft.selectedId : "";
  const [step, setStep] = useState(() => preselectedService ? 3 : categoryMatch ? 2 : (initialDraft.step && initialDraft.step >= 1 && initialDraft.step <= 4 ? initialDraft.step : 1));
  const [category, setCategory] = useState(() => preselectedService ? (categoryName(preselectedService) ?? "") : categoryMatch ? categoryMatch : (initialDraft.category ?? ""));
  const [selectedId, setSelectedId] = useState(() => preselectedService ? preselectedService.id : validDraftService);
  const [lockLevel, setLockLevel] = useState<LockLevel>(() => preselectedService ? "service" : categoryMatch ? "category" : "none");
  const [date, setDate] = useState(()=>initialDraft.date ?? mexicoDate()); const [maxDate] = useState(() => toDateValue(new Date(Date.now() + 60 * 86400000))); const [slots, setSlots] = useState<Slot[]>([]); const [selectedSlot, setSelectedSlot] = useState<Slot | null>(()=>initialDraft.selectedSlot ?? null); const [form, setForm] = useState(()=>initialDraft.form ?? { fullName: "", phone: "", email: "", notes: "" }); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [booking, setBooking] = useState<Booking | null>(null); const [paymentOption, setPaymentOption] = useState<"deposit" | "full" | "none">("deposit");
  const categoryServices = services.filter((service) => categoryName(service) === category); const selected = services.find((service) => service.id === selectedId); const depositPercent = selected ? (selected.deposit_enabled === false ? 0 : selected.deposit_percent ?? (settings?.deposit_enabled ? settings.deposit_percent : 0)) : 0; const estimatedDeposit = selected ? Math.round(selected.price_cents * Number(depositPercent) / 100) : 0; const webPaymentsEnabled = settings?.web_payments_enabled !== false; const canDeposit = Boolean(webPaymentsEnabled && estimatedDeposit && (settings?.online_payment_options ?? ["deposit"]).includes("deposit")); const canPayFull = Boolean(webPaymentsEnabled && (settings?.online_payment_options ?? ["deposit"]).includes("full")); const canBookWithoutPayment = Boolean(settings?.allow_booking_without_online_payment || !webPaymentsEnabled); const effectivePaymentOption = paymentOption === "none" && canBookWithoutPayment ? "none" : canDeposit ? (canPayFull ? paymentOption : "deposit") : canPayFull ? "full" : "none";
  useEffect(() => { if (step === 5) return; sessionStorage.setItem("ola-bonita:booking-draft:v1", JSON.stringify({step,category,selectedId,date,selectedSlot,form})); }, [step,category,selectedId,date,selectedSlot,form]);
  useEffect(() => { if (!selectedId || !date) return; const params = new URLSearchParams({ serviceId: selectedId, date }); fetch(`/api/availability?${params}`).then(async (response) => response.ok ? response.json() : { slots: [] }).then((data) => setSlots(data.slots ?? [])).catch(() => setSlots([])); }, [selectedId, date]);
  const chooseCategory = (value: string) => { setCategory(value); setSelectedId(""); setSelectedSlot(null); setSlots([]); setStep(2); };
  const chooseService = (id: string) => { setSelectedId(id); setSelectedSlot(null); setSlots([]); };
  const changeService = () => { setLockLevel("none"); setSelectedId(""); setSelectedSlot(null); setSlots([]); setStep(1); };
  const changeCategory = () => { setLockLevel("none"); setCategory(""); setSelectedId(""); setSelectedSlot(null); setSlots([]); setStep(1); };
  const time = (slot: Slot) => new Intl.DateTimeFormat(intlLocale(locale), { timeZone: "America/Mexico_City", hour: "2-digit", minute: "2-digit", hour12: locale === "en" }).format(new Date(slot.starts_at));
  const dateLabel = () => new Intl.DateTimeFormat(intlLocale(locale), { timeZone: "America/Mexico_City", weekday: "long", day: "numeric", month: "long" }).format(new Date(`${date}T12:00:00-06:00`));
  function bookingWhatsappUrl(createdBooking: Booking) {
    if (!selectedSlot || !selected) return "";
    const message = locale === "es"
      ? `Hola, acabo de reservar en línea en Ola Bonita.\n\nServicio: ${selected.name}\nFecha: ${dateLabel()}\nHora: ${time(selectedSlot)}\nNombre: ${form.fullName}\nTeléfono: ${form.phone}\nCódigo de reserva: ${createdBooking.public_code}`
      : `Hello, I just booked online at Ola Bonita.\n\nService: ${selected.name}\nDate: ${dateLabel()}\nTime: ${time(selectedSlot)}\nName: ${form.fullName}\nPhone: ${form.phone}\nBooking code: ${createdBooking.public_code}`;
    return getWhatsappLink(locale, message);
  }
  async function submitBooking(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selectedSlot || !selected) return; setBusy(true); setMessage(""); const response = await fetch("/api/bookings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ serviceId: selected.id, startsAt: selectedSlot.starts_at, paymentOption: effectivePaymentOption, ...form }) }); const data = await response.json() as { booking?: Booking; checkout_url?: string; error?: string }; if (!response.ok) setMessage(data.error || t.genericError); else { const createdBooking = data.booking; const whatsappUrl = createdBooking ? bookingWhatsappUrl(createdBooking) : ""; sessionStorage.removeItem("ola-bonita:booking-draft:v1"); if (data.checkout_url) { if (whatsappUrl) sessionStorage.setItem(bookingWhatsappKey, whatsappUrl); window.location.assign(data.checkout_url); } else if (whatsappUrl) { window.location.assign(whatsappUrl); } else { setBooking(createdBooking ?? null); if (data.error) setMessage(data.error); setStep(5); } } setBusy(false); }
  if (step === 5 && booking && selected) return <section className="booking-form booking-success"><p className="eyebrow">{t.successEyebrow}</p><h2>{t.successTitle}</h2><p>{t.successText(booking.public_code)}</p>{message && <p className="access-message">{message}</p>}<div className="booking-receipt"><span>{selected.name}</span><b>{money.format(booking.price_cents / 100)}</b>{booking.deposit_due_cents > 0 && <><span>{t.depositPaid(booking.deposit_percent)}</span><b>{money.format(booking.deposit_due_cents / 100)}</b><span>{t.balanceAtSpa}</span><b>{money.format((booking.price_cents - booking.deposit_due_cents) / 100)}</b></>}</div><button className="button" onClick={() => window.location.assign("/")}>{t.backHome} <span>→</span></button></section>;
  const summary = selected && (step === 3 || step === 4) && (
    <div className="booking-selected-summary">
      <div><span>{t.selectedService}</span><strong>{selected.name}</strong><small>{selected.duration_minutes} {t.minutes} · {money.format(selected.price_cents / 100)}</small></div>
      {lockLevel === "service" && <button type="button" onClick={changeService}>{t.changeService}</button>}
    </div>
  );
  return <section className="booking-form">
    {lockLevel === "service" ? (
      <div className="booking-progress"><span className={step >= 3 ? "active" : ""}>1 {t.steps[2]}</span><span className={step >= 4 ? "active" : ""}>2 {t.steps[3]}</span></div>
    ) : lockLevel === "category" ? (
      <div className="booking-progress"><span className={step >= 2 ? "active" : ""}>1 {t.steps[1]}</span><span className={step >= 3 ? "active" : ""}>2 {t.steps[2]}</span><span className={step >= 4 ? "active" : ""}>3 {t.steps[3]}</span></div>
    ) : (
      <div className="booking-progress"><span className={step >= 1 ? "active" : ""}>1 {t.steps[0]}</span><span className={step >= 2 ? "active" : ""}>2 {t.steps[1]}</span><span className={step >= 3 ? "active" : ""}>3 {t.steps[2]}</span><span className={step >= 4 ? "active" : ""}>4 {t.steps[3]}</span></div>
    )}
    {summary}
    {step === 4 && selected && <fieldset className="pos-methods"><legend>{locale === "es" ? "¿Cómo deseas pagar?" : "How would you like to pay?"}</legend>{canDeposit && <label><input type="radio" name="online-payment" checked={effectivePaymentOption === "deposit"} onChange={() => setPaymentOption("deposit")}/>{locale === "es" ? "Apartado" : "Deposit"} · {money.format(estimatedDeposit / 100)}</label>}{canPayFull && <label><input type="radio" name="online-payment" checked={effectivePaymentOption === "full"} onChange={() => setPaymentOption("full")}/>{locale === "es" ? "Pago completo" : "Full payment"} · {money.format(selected.price_cents / 100)}</label>}{canBookWithoutPayment && <label><input type="radio" name="online-payment" checked={effectivePaymentOption === "none"} onChange={() => setPaymentOption("none")}/>{locale === "es" ? "Reservar sin pagar" : "Reserve without paying"}</label>}</fieldset>}
    {step === 1 && <fieldset><legend>{t.step1Title}</legend><p className="category-hint">{t.step1Hint}</p><div className="booking-categories">{categories.map((item, index) => <button type="button" className="booking-category" onClick={() => chooseCategory(item)} key={item}><small>{String(index + 1).padStart(2, "0")}</small><strong>{item}</strong><span>{t.servicesCount(services.filter((service) => categoryName(service) === item).length)} <b>→</b></span></button>)}</div></fieldset>}
    {step === 2 && <><fieldset><legend>{category}</legend><p className="category-hint">{t.step2Hint}</p><div className="booking-services">{categoryServices.map((service) => <label className="booking-service" key={service.id}><input type="radio" name="service" checked={selectedId === service.id} onChange={() => chooseService(service.id)} /><span className="radio-mark"/><span><strong>{service.name}</strong><small>{service.duration_minutes} min</small></span><b>{money.format(service.price_cents / 100)}</b></label>)}</div></fieldset>{selected && <div className="booking-total"><span>{depositPercent > 0 ? t.depositOf(depositPercent) : t.noDeposit}</span><strong>{depositPercent > 0 ? money.format(estimatedDeposit / 100) : t.paidAtSpa}</strong></div>}<div className="booking-actions"><button type="button" className="back-button" onClick={lockLevel === "category" ? changeCategory : () => setStep(1)}>← {lockLevel === "category" ? t.changeCategory : t.backCategories}</button><button type="button" className="button" disabled={!selected} onClick={() => setStep(3)}>{t.chooseDatetime} <span>→</span></button></div></>}
    {step === 3 && <><fieldset><legend>{t.step3Title}</legend><p className="category-hint">{t.step3Hint}</p><BookingCalendar date={date} min={mexicoDate()} max={maxDate} locale={locale} onSelect={(value) => { setDate(value); setSelectedSlot(null); setSlots([]); }} /><p className="slot-date">{dateLabel()}</p><div className="slot-grid">{slots.map((slot) => <button type="button" key={slot.starts_at} className={selectedSlot?.starts_at === slot.starts_at ? "slot active" : "slot"} onClick={() => setSelectedSlot(slot)}>{time(slot)}</button>)}</div>{!slots.length && <p className="empty-services">{t.noSlots}</p>}</fieldset><div className="booking-actions">{lockLevel !== "service" && <button type="button" className="back-button" onClick={() => setStep(2)}>← {t.backService}</button>}<button type="button" className="button" disabled={!selectedSlot} onClick={() => setStep(4)}>{t.continue} <span>→</span></button></div></>}
    {step === 4 && <form onSubmit={submitBooking}><fieldset><legend>{t.step4Title}</legend><p className="booking-summary">{selected?.name} · {dateLabel()} · {selectedSlot && time(selectedSlot)}</p><div className="customer-fields"><label>{t.fullName}<input required value={form.fullName} onChange={(event) => setForm({ ...form, fullName: event.target.value })}/></label><label>{t.phone}<input required type="tel" value={form.phone} onChange={(event) => setForm({ ...form, phone:event.target.value })}/></label><label>{t.email} <small>{t.optional}</small><input type="email" value={form.email} onChange={(event) => setForm({ ...form, email:event.target.value })}/></label><label>{t.notes} <small>{t.optional}</small><input value={form.notes} onChange={(event) => setForm({ ...form, notes:event.target.value })} placeholder={t.notesPlaceholder}/></label></div></fieldset><div className="booking-total"><span>{effectivePaymentOption === "none" ? (locale === "es" ? "Sin pago online" : "No online payment") : effectivePaymentOption === "full" ? (locale === "es" ? "Pago completo online" : "Full online payment") : t.onlineDeposit}</span>{effectivePaymentOption !== "none" && <strong>{money.format((effectivePaymentOption === "full" ? selected!.price_cents : estimatedDeposit) / 100)}</strong>}{effectivePaymentOption === "deposit" && <small>{t.restAtSpa}</small>}</div><div className="booking-actions"><button type="button" className="back-button" onClick={() => setStep(3)}>← {t.backSchedule}</button><button className="button" disabled={busy}>{busy ? t.sending : t.confirm} <span>→</span></button></div>{message && <p className="access-message">{message}</p>}</form>}
  </section>;
}
