"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import type { Locale } from "@/lib/i18n/locale";
import { intlLocale } from "@/lib/i18n/locale";
import { dictionary } from "@/lib/i18n/dictionary";

type Service = { id: string; name: string; duration_minutes: number; price_cents: number; deposit_enabled: boolean | null; deposit_percent: number | null; category: { name: string } | { name: string }[] | null };
type Settings = { deposit_enabled: boolean; deposit_percent: number } | null;
type Slot = { specialist_id: string | null; starts_at: string; ends_at: string };
type Booking = { public_code: string; price_cents: number; deposit_due_cents: number; deposit_percent: number };
type LockLevel = "none" | "category" | "service";
type BookingDraft = Partial<{ step:number; category:string; selectedId:string; date:string; selectedSlot:Slot; form:{ fullName:string; phone:string; email:string; notes:string } }>;
const categoryName = (service: Service) => Array.isArray(service.category) ? service.category[0]?.name : service.category?.name;
const mexicoDate = () => new Intl.DateTimeFormat("en-CA", { timeZone: "America/Mexico_City", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
const readBookingDraft = (): BookingDraft => { if (typeof window === "undefined") return {}; try { return JSON.parse(sessionStorage.getItem("ola-bonita:booking-draft:v1") || "{}"); } catch { sessionStorage.removeItem("ola-bonita:booking-draft:v1"); return {}; } };

export function BookingServicePicker({ services, settings, locale, preselectedServiceId, preselectedCategory }: { services: Service[]; settings: Settings; locale: Locale; preselectedServiceId?: string; preselectedCategory?: string }) {
  const t = dictionary[locale].booking;
  const money = useMemo(() => new Intl.NumberFormat(intlLocale(locale), { style: "currency", currency: "MXN", maximumFractionDigits: 0 }), [locale]);
  const categories = useMemo(() => [...new Set(services.map(categoryName).filter((name): name is string => Boolean(name)))], [services]);
  const preselectedService = preselectedServiceId ? services.find((service) => service.id === preselectedServiceId) : undefined;
  const categoryMatch = !preselectedService && preselectedCategory && categories.includes(preselectedCategory) ? preselectedCategory : undefined;
  const [initialDraft] = useState(readBookingDraft);
  const validDraftService = initialDraft.selectedId && services.some((service) => service.id === initialDraft.selectedId) ? initialDraft.selectedId : "";
  const [step, setStep] = useState(() => preselectedService ? 3 : categoryMatch ? 2 : (initialDraft.step && initialDraft.step >= 1 && initialDraft.step <= 4 ? initialDraft.step : 1));
  const [category, setCategory] = useState(() => preselectedService ? (categoryName(preselectedService) ?? "") : categoryMatch ? categoryMatch : (initialDraft.category ?? ""));
  const [selectedId, setSelectedId] = useState(() => preselectedService ? preselectedService.id : validDraftService);
  const [lockLevel, setLockLevel] = useState<LockLevel>(() => preselectedService ? "service" : categoryMatch ? "category" : "none");
  const [date, setDate] = useState(()=>initialDraft.date ?? mexicoDate()); const [maxDate] = useState(() => new Date(Date.now() + 60 * 86400000).toISOString().slice(0, 10)); const [slots, setSlots] = useState<Slot[]>([]); const [selectedSlot, setSelectedSlot] = useState<Slot | null>(()=>initialDraft.selectedSlot ?? null); const [form, setForm] = useState(()=>initialDraft.form ?? { fullName: "", phone: "", email: "", notes: "" }); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [booking, setBooking] = useState<Booking | null>(null);
  const categoryServices = services.filter((service) => categoryName(service) === category); const selected = services.find((service) => service.id === selectedId); const depositPercent = selected ? (selected.deposit_enabled === false ? 0 : selected.deposit_percent ?? (settings?.deposit_enabled ? settings.deposit_percent : 0)) : 0; const estimatedDeposit = selected ? Math.round(selected.price_cents * Number(depositPercent) / 100) : 0;
  useEffect(() => { if (step === 5) return; sessionStorage.setItem("ola-bonita:booking-draft:v1", JSON.stringify({step,category,selectedId,date,selectedSlot,form})); }, [step,category,selectedId,date,selectedSlot,form]);
  useEffect(() => { if (!selectedId || !date) return; const params = new URLSearchParams({ serviceId: selectedId, date }); fetch(`/api/availability?${params}`).then(async (response) => response.ok ? response.json() : { slots: [] }).then((data) => setSlots(data.slots ?? [])).catch(() => setSlots([])); }, [selectedId, date]);
  const chooseCategory = (value: string) => { setCategory(value); setSelectedId(""); setSelectedSlot(null); setSlots([]); setStep(2); };
  const chooseService = (id: string) => { setSelectedId(id); setSelectedSlot(null); setSlots([]); };
  const changeService = () => { setLockLevel("none"); setSelectedId(""); setSelectedSlot(null); setSlots([]); setStep(1); };
  const changeCategory = () => { setLockLevel("none"); setCategory(""); setSelectedId(""); setSelectedSlot(null); setSlots([]); setStep(1); };
  const time = (slot: Slot) => new Intl.DateTimeFormat(intlLocale(locale), { timeZone: "America/Mexico_City", hour: "2-digit", minute: "2-digit", hour12: locale === "en" }).format(new Date(slot.starts_at));
  const dateLabel = () => new Intl.DateTimeFormat(intlLocale(locale), { timeZone: "America/Mexico_City", weekday: "long", day: "numeric", month: "long" }).format(new Date(`${date}T12:00:00-06:00`));
  async function submitBooking(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selectedSlot || !selected) return; setBusy(true); setMessage(""); const response = await fetch("/api/bookings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ serviceId: selected.id, startsAt: selectedSlot.starts_at, ...form }) }); const data = await response.json() as { booking?: Booking; checkout_url?: string; error?: string }; if (!response.ok) setMessage(data.error || t.genericError); else { sessionStorage.removeItem("ola-bonita:booking-draft:v1"); if (data.checkout_url) window.location.assign(data.checkout_url); else { setBooking(data.booking ?? null); if (data.error) setMessage(data.error); setStep(5); } } setBusy(false); }
  if (step === 5 && booking && selected) return <section className="booking-form booking-success"><p className="eyebrow">{t.successEyebrow}</p><h2>{t.successTitle}</h2><p>{t.successText(booking.public_code)}</p>{message && <p className="access-message">{message}</p>}<div className="booking-receipt"><span>{selected.name}</span><b>{money.format(booking.price_cents / 100)}</b>{booking.deposit_due_cents > 0 && <><span>{t.depositPaid(booking.deposit_percent)}</span><b>{money.format(booking.deposit_due_cents / 100)}</b><span>{t.balanceAtSpa}</span><b>{money.format((booking.price_cents - booking.deposit_due_cents) / 100)}</b></>}</div><button className="button" onClick={() => window.location.assign("/")}>{t.backHome} <span>→</span></button></section>;
  const summary = selected && (step === 3 || step === 4) && (
    <div className="booking-selected-summary">
      <div><span>{t.selectedService}</span><strong>{selected.name}</strong><small>{selected.duration_minutes} {t.minutes} · {money.format(selected.price_cents / 100)}</small></div>
      {lockLevel === "service" && <button type="button" onClick={changeService}>{t.changeService}</button>}
    </div>
  );
  return <section className="booking-form">
    {lockLevel === "service" ? (
      <div className="booking-progress"><span className={step >= 3 ? "active" : ""}>1 {t.steps[2]}</span><span className={step >= 4 ? "active" : ""}>2 {t.steps[3]}</span></div>
    ) : lockLevel === "category" ? (
      <div className="booking-progress"><span className={step >= 2 ? "active" : ""}>1 {t.steps[1]}</span><span className={step >= 3 ? "active" : ""}>2 {t.steps[2]}</span><span className={step >= 4 ? "active" : ""}>3 {t.steps[3]}</span></div>
    ) : (
      <div className="booking-progress"><span className={step >= 1 ? "active" : ""}>1 {t.steps[0]}</span><span className={step >= 2 ? "active" : ""}>2 {t.steps[1]}</span><span className={step >= 3 ? "active" : ""}>3 {t.steps[2]}</span><span className={step >= 4 ? "active" : ""}>4 {t.steps[3]}</span></div>
    )}
    {summary}
    {step === 1 && <fieldset><legend>{t.step1Title}</legend><p className="category-hint">{t.step1Hint}</p><div className="booking-categories">{categories.map((item, index) => <button type="button" className="booking-category" onClick={() => chooseCategory(item)} key={item}><small>{String(index + 1).padStart(2, "0")}</small><strong>{item}</strong><span>{t.servicesCount(services.filter((service) => categoryName(service) === item).length)} <b>→</b></span></button>)}</div></fieldset>}
    {step === 2 && <><fieldset><legend>{category}</legend><p className="category-hint">{t.step2Hint}</p><div className="booking-services">{categoryServices.map((service) => <label className="booking-service" key={service.id}><input type="radio" name="service" checked={selectedId === service.id} onChange={() => chooseService(service.id)} /><span className="radio-mark"/><span><strong>{service.name}</strong><small>{service.duration_minutes} min</small></span><b>{money.format(service.price_cents / 100)}</b></label>)}</div></fieldset>{selected && <div className="booking-total"><span>{depositPercent > 0 ? t.depositOf(depositPercent) : t.noDeposit}</span><strong>{depositPercent > 0 ? money.format(estimatedDeposit / 100) : t.paidAtSpa}</strong></div>}<div className="booking-actions"><button type="button" className="back-button" onClick={lockLevel === "category" ? changeCategory : () => setStep(1)}>← {lockLevel === "category" ? t.changeCategory : t.backCategories}</button><button type="button" className="button" disabled={!selected} onClick={() => setStep(3)}>{t.chooseDatetime} <span>→</span></button></div></>}
    {step === 3 && <><fieldset><legend>{t.step3Title}</legend><p className="category-hint">{t.step3Hint}</p><label className="date-input">{t.dateLabel}<input type="date" min={mexicoDate()} max={maxDate} value={date} onChange={(event) => { setDate(event.target.value); setSelectedSlot(null); setSlots([]); }} /></label><p className="slot-date">{dateLabel()}</p><div className="slot-grid">{slots.map((slot) => <button type="button" key={slot.starts_at} className={selectedSlot?.starts_at === slot.starts_at ? "slot active" : "slot"} onClick={() => setSelectedSlot(slot)}>{time(slot)}</button>)}</div>{!slots.length && <p className="empty-services">{t.noSlots}</p>}</fieldset><div className="booking-actions">{lockLevel !== "service" && <button type="button" className="back-button" onClick={() => setStep(2)}>← {t.backService}</button>}<button type="button" className="button" disabled={!selectedSlot} onClick={() => setStep(4)}>{t.continue} <span>→</span></button></div></>}
    {step === 4 && <form onSubmit={submitBooking}><fieldset><legend>{t.step4Title}</legend><p className="booking-summary">{selected?.name} · {dateLabel()} · {selectedSlot && time(selectedSlot)}</p><div className="customer-fields"><label>{t.fullName}<input required value={form.fullName} onChange={(event) => setForm({ ...form, fullName: event.target.value })}/></label><label>{t.phone}<input required type="tel" value={form.phone} onChange={(event) => setForm({ ...form, phone:event.target.value })}/></label><label>{t.email} <small>{t.optional}</small><input type="email" value={form.email} onChange={(event) => setForm({ ...form, email:event.target.value })}/></label><label>{t.notes} <small>{t.optional}</small><input value={form.notes} onChange={(event) => setForm({ ...form, notes:event.target.value })} placeholder={t.notesPlaceholder}/></label></div></fieldset>{depositPercent > 0 && <div className="booking-total"><span>{t.onlineDeposit}</span><strong>{money.format(estimatedDeposit / 100)}</strong><small>{t.restAtSpa}</small></div>}<div className="booking-actions"><button type="button" className="back-button" onClick={() => setStep(3)}>← {t.backSchedule}</button><button className="button" disabled={busy}>{busy ? t.sending : t.confirm} <span>→</span></button></div>{message && <p className="access-message">{message}</p>}</form>}
  </section>;
}
