"use client";

import { useState } from "react";
import * as Popover from "@radix-ui/react-popover";
import { CalendarDays, ChevronDown, ChevronLeft, ChevronRight, X } from "lucide-react";
import { endOfDay, endOfMonth, endOfWeek, format, startOfDay, startOfMonth, startOfWeek, subDays, subMonths } from "date-fns";
import { es } from "date-fns/locale";
import { DayPicker, useNavigation, type CaptionProps, type DateRange } from "react-day-picker";

type Preset = "all"|"today"|"yesterday"|"last7"|"thisWeek"|"lastWeek"|"thisMonth"|"lastMonth"|"last3Months"|"last6Months"|"custom";
export type DateRangeFilterValue = { preset:Preset; from?:Date; to?:Date };
type Props = { value:DateRangeFilterValue; onChange:(value:DateRangeFilterValue)=>void; placeholder?:string; minDate?:Date; maxDate?:Date; variant?:"pill"|"button"; className?:string };
const options:Array<{value:Preset;label:string}> = [{value:"today",label:"Hoy"},{value:"yesterday",label:"Ayer"},{value:"last7",label:"Últimos 7 días"},{value:"thisWeek",label:"Esta semana"},{value:"lastWeek",label:"Semana pasada"},{value:"thisMonth",label:"Este mes"},{value:"lastMonth",label:"Mes anterior"},{value:"last3Months",label:"Últimos 3 meses"},{value:"last6Months",label:"Últimos 6 meses"},{value:"all",label:"Cualquier fecha"},{value:"custom",label:"Personalizado"}];
const label = (preset:Preset) => options.find((item)=>item.value===preset)?.label ?? "Fecha";
const day = (date:Date) => startOfDay(date);
function rangeFor(preset:Preset, now:Date):DateRange|undefined { switch(preset) { case "today": return {from:day(now),to:endOfDay(now)}; case "yesterday": { const date=subDays(now,1); return {from:day(date),to:endOfDay(date)}; } case "last7":return {from:day(subDays(now,6)),to:endOfDay(now)}; case "thisWeek":return {from:startOfWeek(now,{weekStartsOn:0}),to:endOfWeek(now,{weekStartsOn:0})}; case "lastWeek": {const date=subDays(now,7);return {from:startOfWeek(date,{weekStartsOn:0}),to:endOfWeek(date,{weekStartsOn:0})};} case "thisMonth":return {from:startOfMonth(now),to:endOfDay(now)}; case "lastMonth": {const date=subMonths(now,1); return {from:startOfMonth(date),to:endOfMonth(date)};} case "last3Months":return {from:day(subMonths(now,3)),to:endOfDay(now)}; case "last6Months":return {from:day(subMonths(now,6)),to:endOfDay(now)}; default:return undefined; } }

function CalendarCaption({ displayMonth, displayIndex = 0 }: CaptionProps) {
  const { goToMonth } = useNavigation();
  return <div className="relative flex h-11 items-center justify-center px-10">
    {displayIndex === 0 && <button type="button" aria-label="Mes anterior" onClick={() => goToMonth(subMonths(displayMonth, 1))} className="absolute left-0 inline-flex h-9 w-9 items-center justify-center rounded-full border border-[#4b7978] text-[#b5cecb] transition hover:bg-[#286061] hover:text-[#f4efe6]"><ChevronLeft className="h-5 w-5" /></button>}
    <span className="capitalize text-lg font-semibold text-[#f4efe6]">{format(displayMonth, "LLLL yyyy", { locale:es })}</span>
    {displayIndex === 1 && <button type="button" aria-label="Mes siguiente" onClick={() => goToMonth(subMonths(displayMonth, -1))} className="absolute right-0 inline-flex h-9 w-9 items-center justify-center rounded-full border border-[#4b7978] text-[#b5cecb] transition hover:bg-[#286061] hover:text-[#f4efe6]"><ChevronRight className="h-5 w-5" /></button>}
  </div>;
}
export function DateRangeFilter({ value,onChange,placeholder="Fecha",minDate,maxDate,variant="pill",className="" }:Props) {
  const [open,setOpen]=useState(false); const now=new Date(); const [draft,setDraft]=useState<DateRange|undefined>(()=>value.preset==="custom"?{from:value.from,to:value.to}:rangeFor(value.preset,now)); const [preset,setPreset]=useState<Preset>(value.preset); const active=value.preset!=="all";
  const text=value.preset==="custom" ? (value.from ? `${format(value.from,"d MMM",{locale:es})}${value.to ? ` – ${format(value.to,"d MMM",{locale:es})}` : ""}` : "Personalizado") : value.preset==="all" ? placeholder : label(value.preset);
  const choose=(next:Preset)=>{setPreset(next); if(next==="custom") return; if(next==="all") { setDraft(undefined); onChange({preset:"all"}); setOpen(false); return; } const range=rangeFor(next,now); setDraft(range); onChange({preset:next}); setOpen(false);};
  const trigger=variant==="pill"?`flex h-8 items-center gap-1.5 rounded-full px-3 text-[13px] font-medium transition ${active?"bg-[#17494a] text-[#f4efe6]":"bg-[#edf5f1] text-[#4c6e6d] hover:bg-[#dfeee8]"}`:`flex h-10 w-full items-center gap-2 rounded-xl border border-[#c8ddd6] bg-white px-3 text-sm text-[#315657] shadow-sm hover:bg-[#f5faf8] ${!active?"text-[#718884]":""}`;
  return <Popover.Root open={open} onOpenChange={(next)=>{ setOpen(next); if(next){ setPreset(value.preset); setDraft(value.preset==="custom" ? {from:value.from,to:value.to} : rangeFor(value.preset,new Date())); } }}>
    <Popover.Trigger asChild><button type="button" className={`${trigger} ${className}`}><CalendarDays className="h-4 w-4"/><span className="truncate">{text}</span>{active ? <span role="button" tabIndex={0} aria-label="Quitar filtro de fecha" onClick={(event)=>{event.stopPropagation();onChange({preset:"all"});}} className="ml-auto rounded-full p-0.5 hover:bg-white/20"><X className="h-3.5 w-3.5"/></span> : <ChevronDown className="ml-auto h-3.5 w-3.5"/>}</button></Popover.Trigger>
    <Popover.Portal><Popover.Content align="end" sideOffset={10} collisionPadding={16} className="z-50 flex w-[min(870px,calc(100vw-32px))] overflow-hidden rounded-[24px] border-2 border-[#4b7978] bg-[#17494a] text-[#f4efe6] shadow-2xl outline-none"><aside className="w-[190px] shrink-0 border-r border-[#4b7978] bg-[#133f40] p-3"><p className="px-2 pb-3 pt-2 text-[11px] font-semibold uppercase tracking-[.12em] text-[#b5cecb]">Periodos</p><div className="grid gap-1">{options.map(item=><button type="button" key={item.value} onClick={()=>choose(item.value)} className={`rounded-xl px-3 py-2 text-left text-[15px] font-medium transition ${preset===item.value?"bg-[#f5ede1] text-[#17494a]":"text-[#eaf0ec] hover:bg-[#286061]"}`}>{item.label}</button>)}</div></aside><section className="min-w-0 flex-1"><DayPicker mode="range" numberOfMonths={2} selected={draft} onSelect={(range)=>{setDraft(range);setPreset("custom");if(range?.from&&range.to){onChange({preset:"custom",from:day(range.from),to:endOfDay(range.to)});setOpen(false);}}} locale={es} weekStartsOn={0} fromDate={minDate} toDate={maxDate??now} className="date-range-calendar p-5" components={{ Caption:CalendarCaption }} classNames={{ months:"flex gap-8", month:"min-w-[280px] space-y-3", caption:"relative flex items-center justify-center", caption_label:"hidden", table:"w-full border-separate border-spacing-y-1", head_row:"grid grid-cols-7", head_cell:"flex h-9 items-center justify-center text-[11px] font-medium text-[#b5cecb]", row:"grid grid-cols-7", cell:"flex h-10 items-center justify-center p-0", day:"h-10 w-10 rounded-full text-[15px] font-medium text-[#f4efe6] transition hover:bg-[#286061]", day_selected:"bg-[#f5ede1] text-[#17494a] hover:bg-[#f5ede1] hover:text-[#17494a]", day_range_middle:"rounded-full bg-[#f5ede1] text-[#17494a] hover:bg-[#f5ede1] hover:text-[#17494a]", day_range_start:"rounded-full bg-[#f5ede1] text-[#17494a] hover:bg-[#f5ede1] hover:text-[#17494a]", day_range_end:"rounded-full bg-[#f5ede1] text-[#17494a] hover:bg-[#f5ede1] hover:text-[#17494a]", day_today:"ring-1 ring-[#dfaa9c]", day_outside:"text-[#759795]", day_disabled:"cursor-not-allowed text-[#527776] opacity-50" }}/><footer className="flex items-center justify-between gap-4 border-t border-[#4b7978] px-5 py-4"><p className="text-sm text-[#b5cecb]">{draft?.from?format(draft.from,"d MMM yyyy",{locale:es}):"Elige una fecha"} – {draft?.to?format(draft.to,"d MMM yyyy",{locale:es}):"Elige la fecha final"}</p><button type="button" onClick={()=>setOpen(false)} className="shrink-0 rounded-xl border border-[#84aaa3] px-4 py-2 text-sm font-semibold text-[#f4efe6] transition hover:bg-[#286061]">Cancelar</button></footer></section></Popover.Content></Popover.Portal>
  </Popover.Root>;
}
