"use client";

import { useMemo, useState } from "react";
import * as Popover from "@radix-ui/react-popover";
import { CalendarDays, ChevronDown, X } from "lucide-react";
import { endOfDay, endOfMonth, endOfWeek, format, startOfDay, startOfMonth, startOfWeek, subDays, subMonths } from "date-fns";
import { es } from "date-fns/locale";
import { DayPicker, type DateRange } from "react-day-picker";

type Preset = "all"|"today"|"yesterday"|"last7"|"thisWeek"|"lastWeek"|"thisMonth"|"lastMonth"|"last3Months"|"last6Months"|"custom";
export type DateRangeFilterValue = { preset:Preset; from?:Date; to?:Date };
type Props = { value:DateRangeFilterValue; onChange:(value:DateRangeFilterValue)=>void; placeholder?:string; minDate?:Date; maxDate?:Date; variant?:"pill"|"button"; className?:string };
const options:Array<{value:Preset;label:string}> = [{value:"today",label:"Hoy"},{value:"yesterday",label:"Ayer"},{value:"last7",label:"Últimos 7 días"},{value:"thisWeek",label:"Esta semana"},{value:"lastWeek",label:"Semana pasada"},{value:"thisMonth",label:"Este mes"},{value:"lastMonth",label:"Mes anterior"},{value:"last3Months",label:"Últimos 3 meses"},{value:"last6Months",label:"Últimos 6 meses"},{value:"all",label:"Cualquier fecha"},{value:"custom",label:"Personalizado"}];
const label = (preset:Preset) => options.find((item)=>item.value===preset)?.label ?? "Fecha";
const day = (date:Date) => startOfDay(date);
function rangeFor(preset:Preset, now:Date):DateRange|undefined { switch(preset) { case "today": return {from:day(now),to:endOfDay(now)}; case "yesterday": { const date=subDays(now,1); return {from:day(date),to:endOfDay(date)}; } case "last7":return {from:day(subDays(now,6)),to:endOfDay(now)}; case "thisWeek":return {from:startOfWeek(now,{weekStartsOn:0}),to:endOfWeek(now,{weekStartsOn:0})}; case "lastWeek": {const date=subDays(now,7);return {from:startOfWeek(date,{weekStartsOn:0}),to:endOfWeek(date,{weekStartsOn:0})};} case "thisMonth":return {from:startOfMonth(now),to:endOfDay(now)}; case "lastMonth": {const date=subMonths(now,1); return {from:startOfMonth(date),to:endOfMonth(date)};} case "last3Months":return {from:day(subMonths(now,3)),to:endOfDay(now)}; case "last6Months":return {from:day(subMonths(now,6)),to:endOfDay(now)}; default:return undefined; } }
export function DateRangeFilter({ value,onChange,placeholder="Fecha",minDate,maxDate,variant="pill",className="" }:Props) {
  const [open,setOpen]=useState(false); const now=useMemo(()=>new Date(),[open]); const [draft,setDraft]=useState<DateRange|undefined>(()=>value.preset==="custom"?{from:value.from,to:value.to}:rangeFor(value.preset,now)); const [preset,setPreset]=useState<Preset>(value.preset); const active=value.preset!=="all";
  const text=value.preset==="custom" ? (value.from ? `${format(value.from,"d MMM",{locale:es})}${value.to ? ` – ${format(value.to,"d MMM",{locale:es})}` : ""}` : "Personalizado") : value.preset==="all" ? placeholder : label(value.preset);
  const choose=(next:Preset)=>{setPreset(next); if(next!=="custom"&&next!=="all") setDraft(rangeFor(next,now)); if(next==="all") setDraft(undefined);};
  const apply=()=>{ if(preset==="all") onChange({preset:"all"}); else if(preset==="custom") { if(!draft?.from) return; onChange({preset:"custom",from:day(draft.from),to:endOfDay(draft.to??draft.from)}); } else onChange({preset}); setOpen(false); };
  const trigger=variant==="pill"?`flex h-8 items-center gap-1.5 rounded-full px-3 text-[13px] font-medium transition ${active?"bg-slate-900 text-white":"bg-slate-100 text-slate-500 hover:bg-slate-200"}`:`flex h-10 w-full items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 text-sm shadow-sm hover:bg-slate-50 ${!active?"text-slate-500":""}`;
  return <Popover.Root open={open} onOpenChange={(next)=>{ setOpen(next); if(next){ setPreset(value.preset); setDraft(value.preset==="custom" ? {from:value.from,to:value.to} : rangeFor(value.preset,new Date())); } }}>
    <Popover.Trigger asChild><button type="button" className={`${trigger} ${className}`}><CalendarDays className="h-4 w-4"/><span className="truncate">{text}</span>{active ? <span role="button" tabIndex={0} aria-label="Quitar filtro de fecha" onClick={(event)=>{event.stopPropagation();onChange({preset:"all"});}} className="ml-auto rounded-full p-0.5 hover:bg-white/20"><X className="h-3.5 w-3.5"/></span> : <ChevronDown className="ml-auto h-3.5 w-3.5"/>}</button></Popover.Trigger>
    <Popover.Portal><Popover.Content align="start" sideOffset={6} className="z-50 flex overflow-hidden rounded-2xl border-2 border-slate-200 bg-white shadow-xl"><aside className="w-[175px] border-r border-slate-200 bg-slate-50 p-2"><p className="px-2 pb-2 pt-1 text-[11px] font-medium uppercase tracking-wider text-slate-500">Periodos</p>{options.map(item=><button type="button" key={item.value} onClick={()=>choose(item.value)} className={`block w-full rounded-md px-2 py-1.5 text-left text-sm ${preset===item.value?"bg-slate-900 text-white":"hover:bg-slate-200"}`}>{item.label}</button>)}</aside><section><DayPicker mode="range" numberOfMonths={2} selected={draft} onSelect={(range)=>{setDraft(range);setPreset("custom");}} locale={es} weekStartsOn={0} showOutsideDays fromDate={minDate} toDate={maxDate??now} className="p-3"/><footer className="flex items-center justify-between border-t border-slate-200 px-3 py-2"><p className="text-xs text-slate-500">{draft?.from?format(draft.from,"d MMM yyyy",{locale:es}):"—"} – {draft?.to?format(draft.to,"d MMM yyyy",{locale:es}):"—"}</p><div className="flex gap-2"><button type="button" onClick={()=>setOpen(false)} className="rounded-md border border-slate-200 px-3 py-1.5 text-sm">Cancelar</button><button type="button" onClick={apply} disabled={preset==="custom"&&!draft?.from} className="rounded-md bg-slate-900 px-3 py-1.5 text-sm text-white disabled:opacity-40">Aplicar</button></div></footer></section></Popover.Content></Popover.Portal>
  </Popover.Root>;
}
