"use client";

import { useState } from "react";
import * as Popover from "@radix-ui/react-popover";
import { CalendarDays, ChevronDown, ChevronLeft, ChevronRight, X } from "lucide-react";
import { endOfDay, endOfMonth, endOfWeek, format, startOfDay, startOfMonth, startOfWeek, subDays, subMonths } from "date-fns";
import { es } from "date-fns/locale";
import { DayPicker, useNavigation, type CaptionProps, type DateRange } from "react-day-picker";

type Preset = "all"|"today"|"yesterday"|"last7"|"thisWeek"|"lastWeek"|"thisMonth"|"lastMonth"|"last3Months"|"last6Months"|"custom";
export type DateRangeFilterValue = { preset:Preset; from?:Date; to?:Date };
type Props = { value:DateRangeFilterValue; onChange:(value:DateRangeFilterValue)=>void; placeholder?:string; minDate?:Date; maxDate?:Date; variant?:"pill"|"button"; className?:string };
const options:Array<{value:Preset;label:string}> = [{value:"today",label:"Hoy"},{value:"yesterday",label:"Ayer"},{value:"last7",label:"Últimos 7 días"},{value:"thisWeek",label:"Esta semana"},{value:"lastWeek",label:"Semana pasada"},{value:"thisMonth",label:"Este mes"},{value:"lastMonth",label:"Mes anterior"},{value:"last3Months",label:"Últimos 3 meses"},{value:"last6Months",label:"Últimos 6 meses"},{value:"all",label:"Cualquier fecha"},{value:"custom",label:"Personalizado"}];
const label = (preset:Preset) => options.find((item)=>item.value===preset)?.label ?? "Fecha";
const day = (date:Date) => startOfDay(date);
function rangeFor(preset:Preset, now:Date):DateRange|undefined { switch(preset) { case "today": return {from:day(now),to:endOfDay(now)}; case "yesterday": { const date=subDays(now,1); return {from:day(date),to:endOfDay(date)}; } case "last7":return {from:day(subDays(now,6)),to:endOfDay(now)}; case "thisWeek":return {from:startOfWeek(now,{weekStartsOn:0}),to:endOfWeek(now,{weekStartsOn:0})}; case "lastWeek": {const date=subDays(now,7);return {from:startOfWeek(date,{weekStartsOn:0}),to:endOfWeek(date,{weekStartsOn:0})};} case "thisMonth":return {from:startOfMonth(now),to:endOfDay(now)}; case "lastMonth": {const date=subMonths(now,1); return {from:startOfMonth(date),to:endOfMonth(date)};} case "last3Months":return {from:day(subMonths(now,3)),to:endOfDay(now)}; case "last6Months":return {from:day(subMonths(now,6)),to:endOfDay(now)}; default:return undefined; } }

function CalendarCaption({ displayMonth, displayIndex = 0 }: CaptionProps) {
  const { goToMonth } = useNavigation();
  return <div className="relative flex h-11 items-center justify-center px-10">
    {displayIndex === 0 && <button type="button" aria-label="Mes anterior" onClick={() => goToMonth(subMonths(displayMonth, 1))} className="absolute left-0 inline-flex h-9 w-9 items-center justify-center rounded-full border border-white/10 text-zinc-300 transition hover:bg-white/10 hover:text-white"><ChevronLeft className="h-5 w-5" /></button>}
    <span className="capitalize text-lg font-semibold text-zinc-100">{format(displayMonth, "LLLL yyyy", { locale:es })}</span>
    {displayIndex === 1 && <button type="button" aria-label="Mes siguiente" onClick={() => goToMonth(subMonths(displayMonth, -1))} className="absolute right-0 inline-flex h-9 w-9 items-center justify-center rounded-full border border-white/10 text-zinc-300 transition hover:bg-white/10 hover:text-white"><ChevronRight className="h-5 w-5" /></button>}
  </div>;
}
export function DateRangeFilter({ value,onChange,placeholder="Fecha",minDate,maxDate,variant="pill",className="" }:Props) {
  const [open,setOpen]=useState(false); const now=new Date(); const [draft,setDraft]=useState<DateRange|undefined>(()=>value.preset==="custom"?{from:value.from,to:value.to}:rangeFor(value.preset,now)); const [preset,setPreset]=useState<Preset>(value.preset); const active=value.preset!=="all";
  const text=value.preset==="custom" ? (value.from ? `${format(value.from,"d MMM",{locale:es})}${value.to ? ` – ${format(value.to,"d MMM",{locale:es})}` : ""}` : "Personalizado") : value.preset==="all" ? placeholder : label(value.preset);
  const choose=(next:Preset)=>{setPreset(next); if(next!=="custom"&&next!=="all") setDraft(rangeFor(next,now)); if(next==="all") setDraft(undefined);};
  const apply=()=>{ if(preset==="all") onChange({preset:"all"}); else if(preset==="custom") { if(!draft?.from) return; onChange({preset:"custom",from:day(draft.from),to:endOfDay(draft.to??draft.from)}); } else onChange({preset}); setOpen(false); };
  const trigger=variant==="pill"?`flex h-8 items-center gap-1.5 rounded-full px-3 text-[13px] font-medium transition ${active?"bg-slate-900 text-white":"bg-slate-100 text-slate-500 hover:bg-slate-200"}`:`flex h-10 w-full items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 text-sm shadow-sm hover:bg-slate-50 ${!active?"text-slate-500":""}`;
  return <Popover.Root open={open} onOpenChange={(next)=>{ setOpen(next); if(next){ setPreset(value.preset); setDraft(value.preset==="custom" ? {from:value.from,to:value.to} : rangeFor(value.preset,new Date())); } }}>
    <Popover.Trigger asChild><button type="button" className={`${trigger} ${className}`}><CalendarDays className="h-4 w-4"/><span className="truncate">{text}</span>{active ? <span role="button" tabIndex={0} aria-label="Quitar filtro de fecha" onClick={(event)=>{event.stopPropagation();onChange({preset:"all"});}} className="ml-auto rounded-full p-0.5 hover:bg-white/20"><X className="h-3.5 w-3.5"/></span> : <ChevronDown className="ml-auto h-3.5 w-3.5"/>}</button></Popover.Trigger>
    <Popover.Portal><Popover.Content align="end" sideOffset={10} collisionPadding={16} className="z-50 flex w-[min(870px,calc(100vw-32px))] overflow-hidden rounded-[24px] border-2 border-zinc-700 bg-[#191919] text-zinc-100 shadow-2xl outline-none"><aside className="w-[190px] shrink-0 border-r border-zinc-700 bg-[#171717] p-3"><p className="px-2 pb-3 pt-2 text-[11px] font-semibold uppercase tracking-[.12em] text-zinc-400">Periodos</p><div className="grid gap-1">{options.map(item=><button type="button" key={item.value} onClick={()=>choose(item.value)} className={`rounded-xl px-3 py-2 text-left text-[15px] font-medium transition ${preset===item.value?"bg-zinc-100 text-zinc-900":"text-zinc-200 hover:bg-zinc-800"}`}>{item.label}</button>)}</div></aside><section className="min-w-0 flex-1"><DayPicker mode="range" numberOfMonths={2} selected={draft} onSelect={(range)=>{setDraft(range);setPreset("custom");}} locale={es} weekStartsOn={0} showOutsideDays fromDate={minDate} toDate={maxDate??now} className="p-5" components={{ Caption:CalendarCaption }} classNames={{ months:"flex gap-8", month:"min-w-[280px] space-y-3", caption:"relative flex items-center justify-center", caption_label:"hidden", table:"w-full border-separate border-spacing-y-1", head_row:"grid grid-cols-7", head_cell:"flex h-9 items-center justify-center text-[11px] font-medium text-zinc-400", row:"grid grid-cols-7", cell:"flex h-10 items-center justify-center p-0", day:"h-10 w-10 rounded-full text-[15px] font-medium text-zinc-100 transition hover:bg-zinc-700", day_selected:"bg-zinc-100 text-zinc-900 hover:bg-zinc-100 hover:text-zinc-900", day_range_middle:"rounded-full bg-zinc-700 text-zinc-100 hover:bg-zinc-600", day_range_start:"rounded-full bg-zinc-100 text-zinc-900 hover:bg-zinc-100", day_range_end:"rounded-full bg-zinc-100 text-zinc-900 hover:bg-zinc-100", day_today:"ring-1 ring-zinc-500", day_outside:"text-zinc-600", day_disabled:"cursor-not-allowed text-zinc-700 opacity-50" }}/><footer className="flex items-center justify-between gap-4 border-t border-zinc-700 px-5 py-4"><p className="text-sm text-zinc-400">{draft?.from?format(draft.from,"d MMM yyyy",{locale:es}):"—"} – {draft?.to?format(draft.to,"d MMM yyyy",{locale:es}):"—"}</p><div className="flex shrink-0 gap-2"><button type="button" onClick={()=>setOpen(false)} className="rounded-xl border border-zinc-600 px-4 py-2 text-sm font-semibold text-zinc-100 transition hover:bg-zinc-800">Cancelar</button><button type="button" onClick={apply} disabled={preset==="custom"&&!draft?.from} className="rounded-xl bg-zinc-100 px-4 py-2 text-sm font-semibold text-zinc-900 transition hover:bg-white disabled:cursor-not-allowed disabled:opacity-40">Actualizar</button></div></footer></section></Popover.Content></Popover.Portal>
  </Popover.Root>;
}
