"use client";

import { useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Settings = { id: string; business_name: string; timezone: string; currency: string; booking_lead_time_minutes: number } | null;

export function AccountSettings({ settings }: { settings: Settings }) {
  const [values, setValues] = useState({ name: settings?.business_name ?? "Ola Bonita Beauty Spa", timezone: settings?.timezone ?? "America/Mexico_City", currency: settings?.currency ?? "MXN", leadTime: settings?.booking_lead_time_minutes ?? 120 });
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function save() { if (!settings) return; setBusy(true); setMessage(""); const { error } = await createClient().from("business_settings").update({ business_name: values.name.trim(), timezone: values.timezone, currency: values.currency, booking_lead_time_minutes: values.leadTime }).eq("id", settings.id); setBusy(false); setMessage(error?.message || "Cuenta y reglas generales guardadas."); }
  return <><header className="settings-header"><div><p className="eyebrow">CUENTA Y NEGOCIO</p><h1>Datos generales</h1><p>La base de tu operación, agenda y cobros.</p></div></header><section className="settings-card settings-form-card account-settings"><h2>Identidad del negocio</h2><p>Estos datos se usan como referencia en la aplicación y en las reservas.</p><label>Nombre comercial<input required value={values.name} onChange={(event) => setValues({ ...values, name: event.target.value })} /></label><div className="field-row"><label>Zona horaria<select value={values.timezone} onChange={(event) => setValues({ ...values, timezone: event.target.value })}><option value="America/Mexico_City">Ciudad de México (UTC−6)</option></select><small>Define los horarios de agenda y reservas.</small></label><label>Moneda<select value={values.currency} onChange={(event) => setValues({ ...values, currency: event.target.value })}><option value="MXN">Peso mexicano (MXN)</option></select><small>Moneda usada en ventas y reportes.</small></label></div></section><section className="settings-card settings-form-card account-settings"><h2>Regla general de reservas</h2><p>Controla con cuánta anticipación se puede reservar desde el sitio web.</p><label>Anticipación mínima<input type="number" min="0" max="43200" value={values.leadTime} onChange={(event) => setValues({ ...values, leadTime: Number(event.target.value) })} /><small>Minutos antes de la cita. Por ejemplo, 120 equivale a 2 horas.</small></label><button type="button" className="new-booking" disabled={busy || !values.name.trim()} onClick={save}>{busy ? "Guardando…" : "Guardar configuración general"}</button>{message && <p className="access-message">{message}</p>}</section></>;
}
