"use client";

import { FormEvent, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { Hint } from "./hint";

type Category = { id:string; name:string; slug:string; active:boolean; sort_order:number };
type Service = { id:string; category_id:string; name:string; description:string|null; duration_minutes:number; price_cents:number; active:boolean; online_bookable:boolean; sort_order:number };
type Product = { id:string; name:string; sku:string|null; price_cents:number; stock_quantity:number|null; active:boolean };
const money = new Intl.NumberFormat("es-MX", { style:"currency", currency:"MXN" });
const slugify = (value:string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

export function CatalogManager({ categories, services, products }: { categories:Category[]; services:Service[]; products:Product[] }) {
  const [serviceList, setServiceList] = useState(services);
  const [productList, setProductList] = useState(products);
  const [categoryList] = useState(categories);
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  const [serviceDraft, setServiceDraft] = useState({ name:"", categoryId:categories[0]?.id ?? "", price:"", duration:"30", description:"", online:true });
  const [productDraft, setProductDraft] = useState({ name:"", sku:"", price:"", stock:"" });
  const [categoryDraft, setCategoryDraft] = useState("");
  const client = createClient();
  const cents = (value:string) => Math.round(Number(value.replace(",", ".")) * 100);
  const save = async (work:() => PromiseLike<{ error:{ message:string }|null }>, success:string) => { setBusy(true); setMessage(""); const { error } = await work(); setBusy(false); setMessage(error?.message || success); return !error; };

  async function addCategory(event:FormEvent) { event.preventDefault(); const name = categoryDraft.trim(); if (!name) return; if (await save(() => client.from("service_categories").insert({ name, slug:slugify(name), sort_order:categoryList.length }), "Categoría agregada.")) window.location.reload(); }
  async function addService(event:FormEvent) { event.preventDefault(); if (!serviceDraft.name || !serviceDraft.categoryId || !serviceDraft.price) return; if (await save(() => client.from("services").insert({ name:serviceDraft.name.trim(), category_id:serviceDraft.categoryId, price_cents:cents(serviceDraft.price), duration_minutes:Number(serviceDraft.duration), description:serviceDraft.description.trim() || null, online_bookable:serviceDraft.online, active:true, sort_order:serviceList.length }), "Servicio agregado.")) window.location.reload(); }
  async function addProduct(event:FormEvent) { event.preventDefault(); if (!productDraft.name || !productDraft.price) return; if (await save(() => client.from("pos_products").insert({ name:productDraft.name.trim(), sku:productDraft.sku.trim() || null, price_cents:cents(productDraft.price), stock_quantity:productDraft.stock === "" ? null : Number(productDraft.stock), active:true }), "Producto agregado al POS.")) window.location.reload(); }
  async function toggleService(service:Service, field:"active"|"online_bookable") { const next = !service[field]; if (await save(() => client.from("services").update({ [field]:next }).eq("id", service.id), "Servicio actualizado.")) setServiceList((current) => current.map((item) => item.id === service.id ? { ...item, [field]:next } : item)); }
  async function toggleProduct(product:Product) { const active = !product.active; if (await save(() => client.from("pos_products").update({ active }).eq("id", product.id), "Producto actualizado.")) setProductList((current) => current.map((item) => item.id === product.id ? { ...item, active } : item)); }
  const categoryName = (id:string) => categoryList.find((category) => category.id === id)?.name || "Sin categoría";

  return <section className="catalog-settings">
    <header className="settings-header compact-settings"><div><p className="eyebrow">CATÁLOGO Y POS</p><h1>Catálogo de servicios</h1><p>Crea servicios para vender y decidir si también se pueden reservar en <strong>olabonita.shop</strong>.</p></div></header>
    <div className="catalog-columns catalog-actions">
      <section className="settings-card catalog-card"><p className="eyebrow">ORGANIZACIÓN</p><h2>Agregar categoría <Hint text="Agrupa servicios parecidos." /></h2><p className="catalog-help">Sirve para agrupar servicios en la web y en el POS.</p><form className="inline-add" onSubmit={addCategory}><input title="Nombre de la categoría" value={categoryDraft} onChange={(event) => setCategoryDraft(event.target.value)} placeholder="Ej. Terapias corporales"/><button className="new-booking" disabled={busy}>Agregar</button></form><div className="category-chips">{categoryList.map((category) => <span key={category.id}>{category.name}</span>)}</div></section>
      <section className="settings-card catalog-card service-add-card"><p className="eyebrow">NUEVO SERVICIO</p><h2>Agregar servicio <Hint text="Se vende desde el punto de venta." /></h2><p className="catalog-help">Al guardarlo se agrega al POS. Activa “Reservable en web” solo si quieres mostrarlo al público.</p><form className="catalog-form" onSubmit={addService}><input required title="Nombre visible del servicio" value={serviceDraft.name} onChange={(event) => setServiceDraft({ ...serviceDraft, name:event.target.value })} placeholder="Nombre del servicio"/><div className="form-columns"><select required title="Grupo del servicio" value={serviceDraft.categoryId} onChange={(event) => setServiceDraft({ ...serviceDraft, categoryId:event.target.value })}>{categoryList.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select><input required title="Tiempo que ocupa en agenda" type="number" min="5" step="5" value={serviceDraft.duration} onChange={(event) => setServiceDraft({ ...serviceDraft, duration:event.target.value })} placeholder="Duración (min)"/><input required title="Precio final para cobrar" inputMode="decimal" value={serviceDraft.price} onChange={(event) => setServiceDraft({ ...serviceDraft, price:event.target.value })} placeholder="Precio MXN"/></div><input title="Texto adicional para clientes" value={serviceDraft.description} onChange={(event) => setServiceDraft({ ...serviceDraft, description:event.target.value })} placeholder="Descripción (opcional)"/><label className="check-label"><input type="checkbox" checked={serviceDraft.online} onChange={(event) => setServiceDraft({ ...serviceDraft, online:event.target.checked })}/> Publicar y permitir reservas en el sitio web <Hint text="Lo muestra en olabonita.shop." /></label><button className="new-booking" disabled={busy || !categoryList.length}>Agregar servicio</button></form></section>
    </div>

    <section className="settings-card catalog-table-card"><div className="catalog-table-head"><div><p className="eyebrow">SERVICIOS</p><h2>Servicios creados</h2><p>Todos se pueden cobrar en el POS. Las dos últimas columnas controlan si se muestran y reservan en la web.</p></div><strong>{serviceList.length} servicios</strong></div><div className="catalog-table-wrap"><table className="catalog-table"><thead><tr><th>Servicio</th><th>Categoría</th><th>Duración</th><th>Precio</th><th>Reservable en web <Hint text="Permite reservarlo desde el sitio." /></th><th>Activo <Hint text="Oculta el servicio al vender." /></th></tr></thead><tbody>{serviceList.map((service) => <tr key={service.id}><td><strong>{service.name}</strong>{service.description && <small>{service.description}</small>}</td><td>{categoryName(service.category_id)}</td><td>{service.duration_minutes} min</td><td>{money.format(service.price_cents / 100)}</td><td><label className="table-toggle"><input type="checkbox" checked={service.online_bookable} onChange={() => toggleService(service, "online_bookable")}/><span>{service.online_bookable ? "Sí" : "No"}</span></label></td><td><label className="table-toggle"><input type="checkbox" checked={service.active} onChange={() => toggleService(service, "active")}/><span>{service.active ? "Activo" : "Pausado"}</span></label></td></tr>)}</tbody></table></div></section>

    <details className="settings-card product-panel"><summary><span><p className="eyebrow">PRODUCTOS DEL POS</p><h2>Productos para vender en mostrador</h2><small>No aparecen en el sitio web ni en reservas.</small></span><b>{productList.length} producto{productList.length === 1 ? "" : "s"} <i>⌄</i></b></summary><div className="product-panel-content"><form className="catalog-form product-form" onSubmit={addProduct}><div className="form-columns"><input required value={productDraft.name} onChange={(event) => setProductDraft({ ...productDraft, name:event.target.value })} placeholder="Nombre del producto"/><input value={productDraft.sku} onChange={(event) => setProductDraft({ ...productDraft, sku:event.target.value })} placeholder="SKU (opcional)"/><input required inputMode="decimal" value={productDraft.price} onChange={(event) => setProductDraft({ ...productDraft, price:event.target.value })} placeholder="Precio MXN"/><input inputMode="numeric" value={productDraft.stock} onChange={(event) => setProductDraft({ ...productDraft, stock:event.target.value })} placeholder="Stock (vacío = sin control)"/></div><button className="new-booking" disabled={busy}>Agregar producto al POS</button></form>{productList.length ? <div className="catalog-table-wrap"><table className="catalog-table"><thead><tr><th>Producto</th><th>SKU</th><th>Precio</th><th>Stock</th><th>Estado</th></tr></thead><tbody>{productList.map((product) => <tr key={product.id}><td><strong>{product.name}</strong></td><td>{product.sku || "—"}</td><td>{money.format(product.price_cents / 100)}</td><td>{product.stock_quantity === null ? "Sin control" : product.stock_quantity}</td><td><label className="table-toggle"><input type="checkbox" checked={product.active} onChange={() => toggleProduct(product)}/><span>{product.active ? "Activo" : "Pausado"}</span></label></td></tr>)}</tbody></table></div> : <p className="empty-services">Aún no hay productos de mostrador.</p>}</div></details>
    {message && <p className="access-message settings-message">{message}</p>}
  </section>;
}
