"use client";

import { FormEvent, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Item = { id:string; name:string; color:string; active:boolean; sort_order:number };
const colors = ["#397c75", "#7287b5", "#bd8b46", "#d9787b", "#9877ad", "#4c9c8b"];

export function FinanceSettings({ categories, tags }: { categories:Item[]; tags:Item[] }) {
  const client = createClient(); const [categoryName, setCategoryName] = useState(""); const [tagName, setTagName] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function add(event:FormEvent, table:"finance_categories"|"finance_tags", name:string, clear:()=>void, length:number) { event.preventDefault(); if (!name.trim()) return; setBusy(true); const { error } = await client.from(table).insert({ name:name.trim(), color:colors[length % colors.length], sort_order:length }); setBusy(false); if (error) return setMessage(error.message); clear(); setMessage("Guardado. Recargando…"); window.setTimeout(() => window.location.reload(), 400); }
  async function toggle(table:"finance_categories"|"finance_tags", item:Item) { setBusy(true); const { error } = await client.from(table).update({ active:!item.active }).eq("id", item.id); setBusy(false); if (error) return setMessage(error.message); window.location.reload(); }
  const block = (title:string, help:string, list:Item[], table:"finance_categories"|"finance_tags", value:string, change:(value:string)=>void, clear:()=>void, placeholder:string) => <section className="settings-card finance-settings-card"><p className="eyebrow">{title.toUpperCase()}</p><h2>{title}</h2><p className="catalog-help">{help}</p><form className="inline-add" onSubmit={(event) => add(event, table, value, clear, list.length)}><input value={value} onChange={(event)=>change(event.target.value)} placeholder={placeholder}/><button className="new-booking" disabled={busy}>Agregar</button></form><div className="finance-tag-list">{list.map((item)=><div key={item.id}><span className="finance-color" style={{ background:item.color }}/><strong>{item.name}</strong><label className="table-toggle"><input type="checkbox" checked={item.active} disabled={busy} onChange={()=>toggle(table,item)}/><span>{item.active ? "Activa" : "Pausada"}</span></label></div>)}</div></section>;
  return <section className="finance-settings"><header><p className="eyebrow">FINANZAS</p><h1>Gastos, categorías y etiquetas</h1><p>Las categorías aparecen como un menú al registrar un gasto. Las etiquetas permiten clasificar cada movimiento como en Spendee.</p></header><div className="finance-settings-grid">{block("Categorías de gasto", "Agrupan el gasto principal: selecciona una al registrarlo.", categories, "finance_categories", categoryName, setCategoryName, ()=>setCategoryName(""), "Ej. Insumos")}{block("Etiquetas", "Puedes seleccionar varias en cada gasto para filtrar y analizar después.", tags, "finance_tags", tagName, setTagName, ()=>setTagName(""), "Ej. Recurrente")}</div>{message && <p className="access-message">{message}</p>}</section>;
}
