"use client";

import { FormEvent, useState } from "react";
import { createClient } from "@/lib/supabase/client";

export function GetnetSettings({ configured }: { configured: boolean }) {
  const [isConfigured, setIsConfigured] = useState(configured);
  const [values, setValues] = useState({ merchantId: "", apiKey: "", webhookSecret: "", mode: "production" as "test" | "production" });
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const { error } = await createClient().rpc("save_getnet_credentials", { p_merchant_id: values.merchantId, p_api_key: values.apiKey, p_webhook_secret: values.webhookSecret, p_mode: values.mode }); setBusy(false); if (error) setMessage(error.message); else { setIsConfigured(true); setValues((current) => ({ ...current, apiKey: "", webhookSecret: "" })); setMessage("Credenciales de Getnet guardadas de forma cifrada."); } }
  return <section className="settings-card integration-card"><div className="integration-top"><div><span className="mp-logo">GN</span><div><h2>Getnet</h2><p>Get Checkout · configuración previa</p></div></div><span className={isConfigured ? "connected" : "not-connected"}>{isConfigured ? "Credenciales guardadas" : "Pendiente"}</span></div><p className="category-hint">Guarda las claves que te entregue Getnet. No se volverán a mostrar y el checkout se habilitará cuando terminemos la conexión técnica.</p><form onSubmit={save} className="payment-credentials"><label>Ambiente<select value={values.mode} onChange={(event) => setValues({ ...values, mode:event.target.value as "test" | "production" })}><option value="test">Pruebas / sandbox</option><option value="production">Producción</option></select></label><label>Merchant ID / comercio <small>requerido</small><input required value={values.merchantId} onChange={(event) => setValues({ ...values, merchantId:event.target.value })} placeholder="ID entregado por Getnet" autoComplete="off"/></label><label>API key o token <small>{isConfigured ? "déjalo vacío para conservarlo" : "requerido"}</small><input required={!isConfigured} type="password" value={values.apiKey} onChange={(event) => setValues({ ...values, apiKey:event.target.value })} autoComplete="new-password"/></label><label>Secreto de webhook <small>{isConfigured ? "déjalo vacío para conservarlo" : "requerido"}</small><input required={!isConfigured} type="password" value={values.webhookSecret} onChange={(event) => setValues({ ...values, webhookSecret:event.target.value })} autoComplete="new-password"/></label><button className="new-booking" disabled={busy}>{busy ? "Guardando…" : isConfigured ? "Actualizar Getnet" : "Guardar credenciales"}</button></form><details className="getnet-help"><summary>Cómo obtener estas claves <b>⌄</b></summary><ol><li>Contrata o solicita la habilitación de <strong>Get Checkout</strong> con Getnet México.</li><li>Pide acceso a <strong>sandbox</strong> y a producción para integración web/API.</li><li>Solicita el Merchant ID, API key/token, el secreto de firma de webhook y la guía técnica mexicana.</li><li>Configura como webhook la URL que te compartiremos al habilitar el checkout.</li></ol><a className="text-link" href="https://www.getnet.mx/nuestros-productos/getcheckout" target="_blank" rel="noreferrer">Abrir Get Checkout de Getnet ↗</a></details>{message && <p className="access-message">{message}</p>}</section>;
}
