"use client";

import { useEffect, useMemo, useState } from "react";
import { DateRangeFilter, type DateRangeFilterValue } from "@/components/DateRangeFilter";

type Sale = { id:string; total_cents:number; customer_id:string|null; booking_id:string|null; created_at:string; status:string };
type SaleItem = { sale_id:string; service_id:string|null; description:string; quantity:number; total_cents:number; unit_price_cents:number };
type Payment = { sale_id:string|null; booking_id:string|null; amount_cents:number; method:"cash"|"card"|"transfer"|"online"; status:string; created_at:string };
type Expense = { id:string; category:string; description:string|null; amount_cents:number; expense_date:string; payment_method:string; created_at:string };
type Booking = { id:string; customer_id:string; service_id:string; specialist_id:string|null; starts_at:string; ends_at:string; status:string; price_cents:number; deposit_due_cents:number; payment_status:string; source:string; created_at:string };
type Service = { id:string; name:string; duration_minutes:number; price_cents:number; category_id:string };
type Specialist = { id:string; full_name:string; color:string; role:string };
type Range = { from:Date; to:Date };

const money = new Intl.NumberFormat("es-MX", { style:"currency", currency:"MXN", maximumFractionDigits:0 });
const dateKey = (value:string|Date) => new Intl.DateTimeFormat("en-CA", { timeZone:"America/Mexico_City" }).format(new Date(value));
const compactDate = (date:Date) => date.toISOString().slice(0, 10);
const sum = <T,>(rows:T[], value:(row:T)=>number) => rows.reduce((total, row) => total + value(row), 0);
const daysBetween = (from:Date, to:Date) => Math.max(1, Math.round((to.getTime() - from.getTime()) / 86400000) + 1);
const paymentName:Record<string,string> = { cash:"Efectivo", card:"Tarjeta", transfer:"Transferencia", online:"Mercado Pago" };
const sourceName:Record<string,string> = { web:"Sitio web", pos:"POS", phone:"Teléfono", walk_in:"Walk-in" };

function resolveRange(value:DateRangeFilterValue):Range {
  const now = new Date(); const end = new Date(now); end.setHours(23,59,59,999);
  if (value.preset === "custom" && value.from) return { from:new Date(value.from), to:new Date(value.to ?? value.from) };
  if (value.preset === "all") return { from:new Date(2000,0,1), to:end };
  const from = new Date(now); from.setHours(0,0,0,0);
  if (value.preset === "today") return { from, to:end };
  if (value.preset === "yesterday") { from.setDate(from.getDate()-1); return { from, to:new Date(from.getTime()+86399999) }; }
  if (value.preset === "last7") { from.setDate(from.getDate()-6); return { from, to:end }; }
  if (value.preset === "lastWeek") { from.setDate(from.getDate()-from.getDay()-7); const to=new Date(from); to.setDate(to.getDate()+6); to.setHours(23,59,59,999); return { from,to }; }
  if (value.preset === "lastMonth") { from.setDate(1); from.setMonth(from.getMonth()-1); const to=new Date(from.getFullYear(),from.getMonth()+1,0,23,59,59,999); return { from,to }; }
  if (value.preset === "last3Months") { from.setMonth(from.getMonth()-3); return { from,to:end }; }
  if (value.preset === "last6Months") { from.setMonth(from.getMonth()-6); return { from,to:end }; }
  if (value.preset === "thisWeek") { from.setDate(from.getDate()-from.getDay()); return { from,to:end }; }
  from.setDate(1); return { from,to:end };
}
function inRange(value:string, range:Range) { const date = new Date(value); return date >= range.from && date <= range.to; }
function minutesBetween(start:string, end:string) { return Math.max(0, (new Date(end).getTime() - new Date(start).getTime()) / 60000); }
function previousRange(range:Range):Range { const size = daysBetween(range.from,range.to); const to = new Date(range.from.getTime()-1); to.setHours(23,59,59,999); const from = new Date(to); from.setDate(from.getDate()-size+1); from.setHours(0,0,0,0); return { from,to }; }

function Metric({ label, value, note, tone="" }: { label:string; value:string|number; note:string; tone?:string }) { return <article className={`analytics-metric ${tone}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>; }
function Empty({ children }: { children:string }) { return <p className="analytics-empty">{children}</p>; }
function HorizontalBars({ data, currency=false }: { data:Array<{label:string; value:number; detail?:string}>; currency?:boolean }) { const max=Math.max(...data.map(item=>item.value),1); return data.length ? <div className="horizontal-bars">{data.slice(0,7).map(item=><div key={item.label}><span>{item.label}</span><i><b style={{ width:`${item.value/max*100}%` }}/></i><strong>{currency ? money.format(item.value/100) : item.value}</strong>{item.detail&&<small>{item.detail}</small>}</div>)}</div> : <Empty>No hay movimientos en este periodo.</Empty>; }
function DonutList({ data }: { data:Array<{label:string; value:number; color?:string}> }) { const total=sum(data,item=>item.value); return data.length ? <div className="donut-layout"><div className="donut" style={{ background:`conic-gradient(${data.slice(0,6).map((item,index)=>`${item.color ?? ["#397c75","#d9787b","#7287b5","#bd8b46","#9877ad","#4c9c8b"][index]} ${(sum(data.slice(0,index), x=>x.value)/total)*100}% ${(sum(data.slice(0,index+1),x=>x.value)/total)*100}%`).join(",")})` }}><span>{money.format(total/100)}</span></div><div className="donut-legend">{data.slice(0,6).map((item,index)=><div key={item.label}><i style={{background:item.color ?? ["#397c75","#d9787b","#7287b5","#bd8b46","#9877ad","#4c9c8b"][index]}}/><span>{item.label}</span><b>{money.format(item.value/100)}</b></div>)}</div></div> : <Empty>Sin datos para graficar.</Empty>; }
function DailyChart({ data }: { data:Array<{ date:string; income:number; expenses:number }> }) { const max=Math.max(...data.flatMap(item=>[item.income,item.expenses]),1); return data.length ? <div className="daily-chart">{data.map(item=><div key={item.date} title={`${item.date}: ${money.format(item.income/100)} ingresos · ${money.format(item.expenses/100)} gastos`}><div className="daily-bars"><i className="income" style={{height:`${item.income/max*100}%`}}/><i className="expenses" style={{height:`${item.expenses/max*100}%`}}/></div><small>{item.date.slice(8)}</small></div>)}</div> : <Empty>Sin actividad en el periodo.</Empty>; }

export function AnalyticsDashboard({ sales, saleItems, payments, expenses, expenseTags, tags, bookings, services, categories, specialists, specialistHours, cabinReservations, cabinHours }: { sales:Sale[]; saleItems:SaleItem[]; payments:Payment[]; expenses:Expense[]; expenseTags:Array<{expense_id:string;tag_id:string}>; tags:Array<{id:string;name:string;color:string}>; bookings:Booking[]; services:Service[]; categories:Array<{id:string;name:string}>; specialists:Specialist[]; specialistHours:Array<{specialist_id:string;day_of_week:number;starts_at:string;ends_at:string;active:boolean}>; cabinReservations:Array<{id:string;full_name:string;starts_at:string;ends_at:string;status:string;price_cents:number;deposit_due_cents:number;payment_status:string;created_at:string}>; cabinHours:Array<{day_of_week:number;opens_at:string;closes_at:string;active:boolean}> }) {
  const [dateFilter,setDateFilter] = useState<DateRangeFilterValue>(() => {
    if (typeof window === "undefined") return { preset:"thisMonth" };
    try { const saved=JSON.parse(sessionStorage.getItem("ola-bonita:analytics-filter") ?? "null"); return saved ? { ...saved, from:saved.from?new Date(saved.from):undefined, to:saved.to?new Date(saved.to):undefined } : { preset:"thisMonth" }; } catch { return { preset:"thisMonth" }; }
  });
  const [filters,setFilters] = useState({ specialist:"all", category:"all", source:"all", payment:"all", expenseCategory:"all", tag:"all", status:"all" });
  const range = useMemo(()=>resolveRange(dateFilter),[dateFilter]);
  useEffect(()=>{ sessionStorage.setItem("ola-bonita:analytics-filter",JSON.stringify({ ...dateFilter, from:dateFilter.from?.toISOString(), to:dateFilter.to?.toISOString() })); },[dateFilter]);

  const serviceById = useMemo(()=>new Map(services.map(item=>[item.id,item])),[services]);
  const categoryById = useMemo(()=>new Map(categories.map(item=>[item.id,item.name])),[categories]);
  const tagById = useMemo(()=>new Map(tags.map(item=>[item.id,item])),[tags]);
  const tagsByExpense = useMemo(()=>expenseTags.reduce((map,item)=>{ map.set(item.expense_id,[...(map.get(item.expense_id)??[]),item.tag_id]); return map; },new Map<string,string[]>()),[expenseTags]);
  const currentSales = sales.filter(item=>inRange(item.created_at,range));
  const currentBookings = bookings.filter(item=>inRange(item.starts_at,range)).filter(item=>(filters.specialist==="all"||item.specialist_id===filters.specialist)&&(filters.source==="all"||item.source===filters.source)&&(filters.status==="all"||item.status===filters.status)&& (filters.category==="all" || categoryById.get(serviceById.get(item.service_id)?.category_id ?? "")===filters.category));
  const currentExpenses = expenses.filter(item=>inRange(`${item.expense_date}T12:00:00`,range)).filter(item=>(filters.expenseCategory==="all"||item.category===filters.expenseCategory)&&(filters.payment==="all"||item.payment_method===filters.payment)&&(filters.tag==="all"||(tagsByExpense.get(item.id)??[]).includes(filters.tag)));
  const saleIdSet = new Set(currentSales.map(item=>item.id));
  const currentItems = saleItems.filter(item=>saleIdSet.has(item.sale_id)).filter(item=> filters.category==="all" || categoryById.get(serviceById.get(item.service_id ?? "")?.category_id ?? "")===filters.category);
  const currentPayments = payments.filter(item=>inRange(item.created_at,range)&&item.status==="completed").filter(item=>filters.payment==="all"||item.method===filters.payment);
  const income = sum(currentPayments,item=>item.amount_cents) || sum(currentSales,item=>item.total_cents);
  const outgoings = sum(currentExpenses,item=>item.amount_cents);
  const net = income-outgoings;
  const done=currentBookings.filter(item=>item.status==="completed").length;
  const cancelled=currentBookings.filter(item=>item.status==="cancelled"||item.status==="no_show").length;
  const outstanding=sum(currentBookings.filter(item=>!["paid","refunded"].includes(item.payment_status)),item=>Math.max(0,item.price_cents-item.deposit_due_cents));
  const availableMinutes=sum(specialistHours,item=>minutesBetween(`2000-01-01T${item.starts_at}`,`2000-01-01T${item.ends_at}`))*Math.max(1,Math.ceil(daysBetween(range.from,range.to)/7));
  const bookedMinutes=sum(currentBookings.filter(item=>!["cancelled","no_show"].includes(item.status)),item=>minutesBetween(item.starts_at,item.ends_at));
  const occupancy=availableMinutes?Math.min(100,Math.round(bookedMinutes/availableMinutes*100)):0;
  const prior=previousRange(range); const priorSales=sales.filter(item=>inRange(item.created_at,prior)); const priorExpenses=expenses.filter(item=>inRange(`${item.expense_date}T12:00:00`,prior)); const priorIncome=sum(priorSales,item=>item.total_cents); const priorOutgoings=sum(priorExpenses,item=>item.amount_cents);
  const dayCount=daysBetween(range.from,range.to); const trend=Array.from({length:Math.min(dayCount,62)},(_,index)=>{ const date=new Date(range.from); date.setDate(date.getDate()+index); const key=compactDate(date); return { date:key, income:sum(currentPayments.filter(item=>dateKey(item.created_at)===key),item=>item.amount_cents), expenses:sum(currentExpenses.filter(item=>item.expense_date===key),item=>item.amount_cents) }; });
  const groupItems=(by:"income"|"quantity")=>Object.values(currentItems.reduce<Record<string,{label:string;value:number;quantity:number;income:number;duration:number}>>((map,item)=>{ const service=serviceById.get(item.service_id??""); const key=item.service_id??item.description; const existing=map[key]??{label:service?.name??item.description,value:0,quantity:0,income:0,duration:service?.duration_minutes??0}; existing.quantity+=item.quantity; existing.income+=item.total_cents; existing.value=by==="income"?existing.income:existing.quantity; map[key]=existing; return map;},{})).sort((a,b)=>b.value-a.value);
  const topIncome=groupItems("income"); const topQuantity=groupItems("quantity");
  const categorySales=Object.values(currentItems.reduce<Record<string,{label:string;value:number}>>((map,item)=>{ const category=categoryById.get(serviceById.get(item.service_id??"")?.category_id??"")??"Productos"; map[category]??={label:category,value:0};map[category].value+=item.total_cents;return map;},{}));
  const paymentMix=Object.entries(currentPayments.reduce<Record<string,number>>((map,item)=>{map[item.method]=(map[item.method]??0)+item.amount_cents;return map;},{})).map(([method,value])=>({label:paymentName[method]??method,value}));
  const expenseByCategory=Object.values(currentExpenses.reduce<Record<string,{label:string;value:number}>>((map,item)=>{map[item.category]??={label:item.category,value:0};map[item.category].value+=item.amount_cents;return map;},{}));
  const expenseByTag=Object.values(currentExpenses.flatMap(item=>(tagsByExpense.get(item.id)??[]).map(tagId=>({tag:tagById.get(tagId),value:item.amount_cents}))).reduce<Record<string,{label:string;value:number;color:string}>>((map,item)=>{if(!item.tag)return map;map[item.tag.id]??={label:item.tag.name,value:0,color:item.tag.color};map[item.tag.id].value+=item.value;return map;},{}));
  const heatmap=Array.from({length:7},(_,day)=>Array.from({length:10},(_,hour)=>({day,hour:hour+9,value:currentBookings.filter(item=>new Date(item.starts_at).getDay()===day&&new Date(item.starts_at).getHours()===hour+9&&!["cancelled","no_show"].includes(item.status)).length})));
  const specialistStats=specialists.filter(item=>item.role==="specialist").map(person=>{const personBookings=currentBookings.filter(item=>item.specialist_id===person.id&&!["cancelled","no_show"].includes(item.status));const hours=personBookings.reduce((total,item)=>total+minutesBetween(item.starts_at,item.ends_at),0);const capacity=sum(specialistHours.filter(item=>item.specialist_id===person.id),item=>minutesBetween(`2000-01-01T${item.starts_at}`,`2000-01-01T${item.ends_at}`))*Math.max(1,Math.ceil(dayCount/7));const personIncome=sum(currentSales.filter(item=>item.booking_id&&personBookings.some(booking=>booking.id===item.booking_id)),item=>item.total_cents);return {person,hours,capacity,income:personIncome,bookings:personBookings.length};});
  const currentCabin=cabinReservations.filter(item=>inRange(item.starts_at,range)); const cabinMinutes=sum(currentCabin.filter(item=>item.status!=="cancelled"),item=>minutesBetween(item.starts_at,item.ends_at)); const cabinCapacity=sum(cabinHours,item=>minutesBetween(`2000-01-01T${item.opens_at}`,`2000-01-01T${item.closes_at}`))*Math.max(1,Math.ceil(dayCount/7));
  const expenseCategories=[...new Set(expenses.map(item=>item.category))];

  return <>
    <header className="ops-header analytics-header"><div><p className="eyebrow">ANALÍTICA</p><h1>Visión del negocio <span>✦</span></h1><p>Ventas, operación y decisiones en un solo lugar.</p></div><DateRangeFilter value={dateFilter} onChange={setDateFilter} placeholder="Periodo" variant="button" className="analytics-date-filter"/></header>
    <section className="analytics-filters"><select value={filters.specialist} onChange={event=>setFilters({...filters,specialist:event.target.value})}><option value="all">Todo el equipo</option>{specialists.filter(item=>item.role==="specialist").map(item=><option key={item.id} value={item.id}>{item.full_name}</option>)}</select><select value={filters.category} onChange={event=>setFilters({...filters,category:event.target.value})}><option value="all">Todas las categorías</option>{categories.map(item=><option key={item.id}>{item.name}</option>)}</select><select value={filters.source} onChange={event=>setFilters({...filters,source:event.target.value})}><option value="all">Todas las fuentes</option>{Object.entries(sourceName).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select><select value={filters.payment} onChange={event=>setFilters({...filters,payment:event.target.value})}><option value="all">Todos los pagos</option>{Object.entries(paymentName).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select><select value={filters.expenseCategory} onChange={event=>setFilters({...filters,expenseCategory:event.target.value})}><option value="all">Todos los gastos</option>{expenseCategories.map(item=><option key={item}>{item}</option>)}</select><select value={filters.tag} onChange={event=>setFilters({...filters,tag:event.target.value})}><option value="all">Todas las etiquetas</option>{tags.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={filters.status} onChange={event=>setFilters({...filters,status:event.target.value})}><option value="all">Todos los estados</option><option value="completed">Realizada</option><option value="confirmed">Confirmada</option><option value="cancelled">Cancelada</option><option value="no_show">No-show</option></select></section>
    <section className="analytics-metric-grid"><Metric label="INGRESOS COBRADOS" value={money.format(income/100)} note="Pagos confirmados"/><Metric label="GASTOS" value={money.format(outgoings/100)} note="Operación registrada" tone="expense"/><Metric label="UTILIDAD NETA" value={money.format(net/100)} note="Antes de impuestos" tone={net>=0?"success":"expense"}/><Metric label="CITAS" value={`${done} / ${cancelled}`} note="Realizadas / canceladas"/><Metric label="SALDO PENDIENTE" value={money.format(outstanding/100)} note="Reservas por liquidar"/><Metric label="OCUPACIÓN" value={`${occupancy}%`} note={`${Math.round(bookedMinutes/60)} h reservadas`} /></section>
    <section className="analytics-card trend-card"><div className="analytics-card-head"><div><p className="eyebrow">DASHBOARD EJECUTIVO</p><h2>Ingresos vs gastos por día</h2><p>Verde: cobrado · Coral: gasto</p></div><div className="trend-legend"><span><i className="income"/>Ingresos</span><span><i className="expenses"/>Gastos</span></div></div><DailyChart data={trend}/></section>
    <section className="analytics-section"><header><p className="eyebrow">VENTAS Y SERVICIOS</p><h2>Qué está generando el negocio</h2></header><div className="analytics-grid two"><article className="analytics-card"><h3>Servicios con más ingreso</h3><HorizontalBars data={topIncome} currency/></article><article className="analytics-card"><h3>Servicios más vendidos</h3><HorizontalBars data={topQuantity}/></article><article className="analytics-card"><h3>Ventas por categoría</h3><DonutList data={categorySales}/></article><article className="analytics-card"><h3>Métodos de pago</h3><HorizontalBars data={paymentMix} currency/></article></div><article className="analytics-card analytics-table-card"><h3>Servicios con oportunidad</h3><div className="analytics-table-wrap"><table><thead><tr><th>Servicio</th><th>Precio</th><th>Cantidad</th><th>Ingreso</th><th>Duración</th><th>Ingreso/hora</th></tr></thead><tbody>{topIncome.slice(0,12).map(item=><tr key={item.label}><td>{item.label}</td><td>{money.format((item.quantity?item.income/item.quantity:0)/100)}</td><td>{item.quantity}</td><td>{money.format(item.income/100)}</td><td>{item.duration||"—"} min</td><td>{item.duration?money.format(item.income/(item.quantity*item.duration)*60/100):"—"}</td></tr>)}</tbody></table></div></article></section>
    <section className="analytics-section"><header><p className="eyebrow">FINANZAS</p><h2>Flujo, gastos y alertas</h2></header><div className="analytics-grid two"><article className="analytics-card"><h3>Flujo neto diario</h3><DailyChart data={trend.map(item=>({...item,income:Math.max(0,item.income-item.expenses),expenses:item.expenses>item.income?item.expenses-item.income:0}))}/></article><article className="analytics-card"><h3>Gastos por categoría</h3><DonutList data={expenseByCategory}/></article><article className="analytics-card"><h3>Gastos por etiqueta</h3><DonutList data={expenseByTag}/></article><article className="analytics-card comparison-card"><h3>Periodo vs anterior</h3>{[["Ingresos",income,priorIncome],["Gastos",outgoings,priorOutgoings],["Utilidad",net,priorIncome-priorOutgoings]].map(([label,current,old])=><div key={String(label)}><span>{label}</span><strong>{money.format(Number(current)/100)}</strong><small>{Number(current)>=Number(old)?"▲":"▼"} vs {money.format(Number(old)/100)}</small></div>)}</article></div><article className="analytics-card analytics-table-card"><h3>Gasto detallado</h3><div className="analytics-table-wrap"><table><thead><tr><th>Fecha</th><th>Categoría</th><th>Etiquetas</th><th>Método</th><th>Descripción</th><th>Importe</th></tr></thead><tbody>{currentExpenses.slice(0,30).map(item=><tr key={item.id}><td>{item.expense_date}</td><td>{item.category}</td><td>{(tagsByExpense.get(item.id)??[]).map(id=>tagById.get(id)?.name).filter(Boolean).join(", ")||"—"}</td><td>{paymentName[item.payment_method]??item.payment_method}</td><td>{item.description||"—"}</td><td>{money.format(item.amount_cents/100)}</td></tr>)}</tbody></table></div></article><article className="analytics-card alerts-card"><h3>Alertas</h3><div><strong>{outstanding ? `${money.format(outstanding/100)} pendiente por cobrar` : "Sin saldos pendientes"}</strong><span>Revisa reservas sin pago completo.</span></div><div><strong>{currentExpenses.length && outgoings > priorOutgoings ? "Gasto mayor al periodo anterior" : "Gasto bajo control"}</strong><span>{money.format(outgoings/100)} frente a {money.format(priorOutgoings/100)}.</span></div><div><strong>Cortes de caja</strong><span>El efectivo contado se compara al cerrar caja.</span></div></article></section>
    <section className="analytics-section"><header><p className="eyebrow">AGENDA Y OPERACIÓN</p><h2>Demanda y capacidad del equipo</h2></header><div className="analytics-grid two"><article className="analytics-card"><h3>Heatmap de demanda</h3><div className="heatmap"><div></div>{["Dom","Lun","Mar","Mié","Jue","Vie","Sáb"].map(day=><b key={day}>{day}</b>)}{Array.from({length:10},(_,index)=><><span key={`h${index}`}>{index+9}:00</span>{heatmap.map((day)=><i key={`${day[index].day}-${index}`} style={{opacity:.12+day[index].value*.22}} title={`${["Domingo","Lunes","Martes","Miércoles","Jueves","Viernes","Sábado"][day[index].day]} ${index+9}:00 · ${day[index].value} reservas`}/>)}</>)}</div></article><article className="analytics-card"><h3>Embudo de reservas</h3><div className="funnel">{[["Creadas",currentBookings.length],["Anticipo pagado",currentBookings.filter(item=>["deposit_paid","paid"].includes(item.payment_status)).length],["Confirmadas",currentBookings.filter(item=>item.status==="confirmed").length],["Realizadas",done],["Canceladas / no-show",cancelled]].map(([label,value],index)=><div key={String(label)} style={{width:`${100-index*11}%`}}><span>{label}</span><b>{value}</b></div>)}</div></article><article className="analytics-card specialist-card"><h3>Ocupación por especialista</h3>{specialistStats.length ? specialistStats.map(stat=><div key={stat.person.id}><span className="specialist-color" style={{background:stat.person.color}}/><strong>{stat.person.full_name}</strong><i><b style={{width:`${stat.capacity?Math.min(100,stat.hours/stat.capacity*100):0}%`}}/></i><small>{Math.round(stat.hours/60)} h / {Math.round(stat.capacity/60)} h · {Math.round(stat.capacity?stat.hours/stat.capacity*100:0)}%</small></div>) : <Empty>Agrega especialistas para ver su carga.</Empty>}</article><article className="analytics-card"><h3>Reservas por fuente</h3><HorizontalBars data={Object.entries(currentBookings.reduce<Record<string,number>>((map,item)=>{map[item.source]=(map[item.source]??0)+1;return map;},{})).map(([label,value])=>({label:sourceName[label]??label,value}))}/></article></div></section>
    <section className="analytics-section"><header><p className="eyebrow">EQUIPO, CLIENTES Y CABINA</p><h2>Vista completa de capacidad</h2></header><div className="analytics-grid three"><article className="analytics-card"><h3>Equipo</h3>{specialistStats.map(stat=><div className="team-stat" key={stat.person.id}><strong>{stat.person.full_name}</strong><span>{money.format(stat.income/100)} · {stat.bookings} servicios</span><small>Ticket: {money.format((stat.bookings?stat.income/stat.bookings:0)/100)}</small></div>) || <Empty>Sin actividad de equipo.</Empty>}</article><article className="analytics-card"><h3>Clientes</h3><div className="customer-insights"><strong>{new Set(currentBookings.map(item=>item.customer_id)).size}</strong><span>clientes atendidos</span><p>{new Set(currentSales.filter(item=>item.customer_id).map(item=>item.customer_id)).size} con compra registrada</p><p>Usa el listado para reactivar quienes no regresan.</p></div></article><article className="analytics-card"><h3>Cabina de masajes</h3><div className="cabin-insights"><strong>{cabinCapacity?Math.round(cabinMinutes/cabinCapacity*100):0}%</strong><span>ocupación</span><p>{money.format(sum(currentCabin.filter(item=>item.status!=="cancelled"),item=>item.price_cents)/100)} en renta</p><p>{currentCabin.filter(item=>item.payment_status!=="paid").length} apartados pendientes · {currentCabin.filter(item=>item.status==="cancelled").length} cancelaciones</p></div></article></div></section>
  </>;
}
