import Link from "next/link";
import { redirect } from "next/navigation";
import { createServerClient } from "@/lib/supabase/server";
export const dynamic = "force-dynamic";
const money = new Intl.NumberFormat("es-MX", { style: "currency", currency: "MXN" });
export default async function FinancePage() {
 const supabase = await createServerClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/app/acceso"); const since = new Date(); since.setDate(since.getDate() - 29); const date = since.toISOString().slice(0, 10);
 const [{ data: profile }, { data: sales }, { data: expenses }] = await Promise.all([supabase.from("profiles").select("full_name,role").eq("id", user.id).single(), supabase.from("sales").select("total_cents").eq("status", "completed").gte("created_at", `${date}T00:00:00Z`), supabase.from("expenses").select("id,category,description,amount_cents,expense_date,payment_method").gte("expense_date", date).order("expense_date", { ascending: false }).limit(12)]);
 if (!profile || !["owner", "manager", "reception"].includes(profile.role)) redirect("/app"); const income = (sales ?? []).reduce((sum, sale) => sum + sale.total_cents, 0); const outgoings = (expenses ?? []).reduce((sum, expense) => sum + expense.amount_cents, 0);
 return <main className="ops-shell"><aside className="sidebar"><Link href="/" className="brand"><span>Ola</span> Bonita<small>BEAUTY SPA</small></Link><nav><Link href="/app">▦ <span>Agenda</span></Link><Link href="/app/equipo">♙ <span>Equipo</span></Link><Link href="/app/operacion">◇ <span>Ventas y caja</span></Link><Link className="active" href="/app/finanzas">◔ <span>Finanzas</span></Link><Link href="/app/cabina">▣ <span>Renta de cabina</span></Link><Link href="/app/configuracion">⚙ <span>Configuración</span></Link></nav><div className="sidebar-user"><span className="avatar">{profile.full_name.slice(0, 2).toUpperCase()}</span><div><strong>{profile.full_name}</strong><small>Equipo Ola Bonita</small></div></div></aside><section className="ops-main"><header className="ops-header"><div><p className="eyebrow">FINANZAS</p><h1>Resumen de 30 días <span>✦</span></h1></div><Link className="new-booking" href="/app/operacion">+ Nueva venta</Link></header><section className="metric-grid finance-metrics"><article><span>INGRESOS</span><strong>{money.format(income / 100)}</strong><small>Ventas completadas</small></article><article><span>GASTOS</span><strong>{money.format(outgoings / 100)}</strong><small>Operación registrada</small></article><article><span>RESULTADO NETO</span><strong>{money.format((income - outgoings) / 100)}</strong><small>Antes de impuestos</small></article></section><section className="agenda-section finance-list"><div className="section-top"><div><h2>Gastos recientes</h2><p>Últimos movimientos registrados</p></div></div>{expenses?.length ? <div className="agenda-list">{expenses.map((expense) => <article className="agenda-row" key={expense.id}><time>{new Intl.DateTimeFormat("es-MX", { day: "2-digit", month: "short", timeZone: "America/Mexico_City" }).format(new Date(`${expense.expense_date}T12:00:00`))}</time><span className="booking-dot mint"/><div className="booking-details"><strong>{expense.category}</strong><span>{expense.description || expense.payment_method}</span></div><span className="booking-status">− {money.format(expense.amount_cents / 100)}</span></article>)}</div> : <div className="empty-agenda"><strong>Aún no hay gastos registrados.</strong><span>Regístralos desde Ventas y caja para que este resumen y el corte estén al día.</span></div>}</section></section></main>;
}
