-- Atomic operations for the reception point of sale and cash register.
create or replace function public.open_cash_session(p_opening_float_cents integer default 0) returns public.cash_sessions language plpgsql security definer set search_path = public as $$ declare v_session public.cash_sessions; begin if not public.is_front_desk() then raise exception 'No tienes permisos para abrir caja'; end if; if p_opening_float_cents < 0 then raise exception 'El fondo inicial no puede ser negativo'; end if; if exists (select 1 from public.cash_sessions where status = 'open') then raise exception 'Ya hay una caja abierta'; end if; insert into public.cash_sessions (opened_by, opening_float_cents, expected_cash_cents) values (auth.uid(), p_opening_float_cents, p_opening_float_cents) returning * into v_session; return v_session; end; $$;

create or replace function public.close_cash_session(p_counted_cash_cents integer, p_notes text default null) returns table(session_id uuid, expected_cash_cents integer, counted_cash_cents integer, variance_cents integer) language plpgsql security definer set search_path = public as $$ declare v_session public.cash_sessions; v_expected integer; begin if not public.is_front_desk() then raise exception 'No tienes permisos para cerrar caja'; end if; if p_counted_cash_cents < 0 then raise exception 'El efectivo contado no puede ser negativo'; end if; select * into v_session from public.cash_sessions where status = 'open' order by opened_at desc limit 1 for update; if v_session.id is null then raise exception 'No hay una caja abierta'; end if; select v_session.opening_float_cents + coalesce(sum(amount_cents), 0) into v_expected from public.payments where payment_method = 'cash' and status = 'completed' and created_at >= v_session.opened_at; select v_expected - coalesce(sum(amount_cents), 0) into v_expected from public.expenses where payment_method = 'cash' and created_at >= v_session.opened_at; update public.cash_sessions set status = 'closed', closed_at = now(), closed_by = auth.uid(), expected_cash_cents = v_expected, counted_cash_cents = p_counted_cash_cents, notes = p_notes where id = v_session.id; return query select v_session.id, v_expected, p_counted_cash_cents, p_counted_cash_cents - v_expected; end; $$;

create or replace function public.record_pos_sale(p_items jsonb, p_payment_method public.payment_method, p_customer_name text default null, p_customer_phone text default null) returns table(sale_id uuid, total_cents integer) language plpgsql security definer set search_path = public as $$ declare v_total integer; v_sale_id uuid; v_customer_id uuid; begin if not public.is_front_desk() then raise exception 'No tienes permisos para registrar ventas'; end if; if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then raise exception 'Agrega al menos un servicio a la venta'; end if; if p_payment_method = 'cash' and not exists (select 1 from public.cash_sessions where status = 'open') then raise exception 'Abre caja antes de registrar pagos en efectivo'; end if; select coalesce(sum(s.price_cents * i.quantity), 0) into v_total from jsonb_to_recordset(p_items) as i(service_id uuid, quantity integer) join public.services s on s.id = i.service_id and s.active where i.quantity > 0; if v_total <= 0 then raise exception 'Los servicios seleccionados no están disponibles'; end if; if nullif(trim(coalesce(p_customer_name, '')), '') is not null then insert into public.customers (full_name, phone) values (trim(p_customer_name), nullif(trim(coalesce(p_customer_phone, '')), '')) returning id into v_customer_id; end if; insert into public.sales (customer_id, status, total_cents, created_by) values (v_customer_id, 'completed', v_total, auth.uid()) returning id into v_sale_id; insert into public.sale_items (sale_id, service_id, description, quantity, unit_price_cents, total_cents) select v_sale_id, s.id, s.name, i.quantity, s.price_cents, s.price_cents * i.quantity from jsonb_to_recordset(p_items) as i(service_id uuid, quantity integer) join public.services s on s.id = i.service_id and s.active where i.quantity > 0; insert into public.payments (sale_id, amount_cents, payment_method, status, paid_at) values (v_sale_id, v_total, p_payment_method, 'completed', now()); return query select v_sale_id, v_total; end; $$;

create or replace function public.record_expense(p_category text, p_description text, p_amount_cents integer, p_payment_method public.payment_method, p_expense_date date default current_date) returns public.expenses language plpgsql security definer set search_path = public as $$ declare v_expense public.expenses; begin if not public.is_front_desk() then raise exception 'No tienes permisos para registrar gastos'; end if; if p_amount_cents <= 0 or nullif(trim(coalesce(p_category, '')), '') is null then raise exception 'Completa la categoría y un importe válido'; end if; if p_payment_method = 'cash' and not exists (select 1 from public.cash_sessions where status = 'open') then raise exception 'Abre caja antes de registrar un gasto en efectivo'; end if; insert into public.expenses (category, description, amount_cents, payment_method, expense_date, created_by) values (trim(p_category), nullif(trim(coalesce(p_description, '')), ''), p_amount_cents, p_payment_method, coalesce(p_expense_date, current_date), auth.uid()) returning * into v_expense; return v_expense; end; $$;

grant execute on function public.open_cash_session(integer) to authenticated;
grant execute on function public.close_cash_session(integer, text) to authenticated;
grant execute on function public.record_pos_sale(jsonb, public.payment_method, text, text) to authenticated;
grant execute on function public.record_expense(text, text, integer, public.payment_method, date) to authenticated;
